// Generated by scripts/generate-service-request-client.js from docs/dev/contracts/service-request.v1.schema.json.
// Do not edit by hand.

export type ServiceRequestAction =
  | "navigate"
  | "cdp_free_launch"
  | "back"
  | "forward"
  | "reload"
  | "tab_new"
  | "tab_switch"
  | "tab_close"
  | "tab_list"
  | "url"
  | "title"
  | "viewport"
  | "user_agent"
  | "emulatemedia"
  | "timezone"
  | "locale"
  | "geolocation"
  | "permissions"
  | "cookies_get"
  | "cookies_set"
  | "cookies_clear"
  | "storage_get"
  | "storage_set"
  | "storage_clear"
  | "console"
  | "errors"
  | "setcontent"
  | "headers"
  | "offline"
  | "dialog"
  | "clipboard"
  | "upload"
  | "download"
  | "waitfordownload"
  | "pdf"
  | "responsebody"
  | "har_start"
  | "har_stop"
  | "route"
  | "unroute"
  | "requests"
  | "request_detail"
  | "snapshot"
  | "screenshot"
  | "click"
  | "fill"
  | "wait"
  | "type"
  | "press"
  | "hover"
  | "select"
  | "gettext"
  | "inputvalue"
  | "isvisible"
  | "getattribute"
  | "innerhtml"
  | "styles"
  | "count"
  | "boundingbox"
  | "isenabled"
  | "ischecked"
  | "check"
  | "uncheck"
  | "scroll"
  | "scrollintoview"
  | "focus"
  | "clear";

export interface ServiceRequest {
  action: ServiceRequestAction;
  params?: Record<string, unknown>;
  profileLeasePolicy?: string;
  browserBuild?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
  targetServiceId?: string;
  targetService?: string;
  siteId?: string;
  loginId?: string;
  accountId?: string;
  url?: string;
  profile?: string;
  runtimeProfile?: string;
  targetServiceIds?: string[];
  targetServices?: string[];
  siteIds?: string[];
  loginIds?: string[];
  accountIds?: string[];
  jobTimeoutMs?: number;
  profileLeaseWaitTimeoutMs?: number;
  blockedByManualAction?: boolean;
  manualSeedingRequired?: boolean;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  requiresCdpFree?: boolean;
  cdpAttachmentAllowed?: boolean;
  monitorRunDueSummary?: Record<string, unknown>;
}

export type ServiceRequestForAction<TAction extends ServiceRequestAction> =
  Omit<ServiceRequest, "action"> & { action: TAction };

export interface ServiceRequestMcpToolCall {
  name: "service_request";
  arguments: ServiceRequest;
}

export interface ServiceRequestHttpOptions<TRequest extends ServiceRequest = ServiceRequest> {
  baseUrl: string;
  request: TRequest;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceNavigateData {
  url: string;
  title?: string;
}

export interface ServiceCdpFreeLaunchData {
  launched: true;
  cdpFree: true;
  cdpAttachmentAllowed: false;
  browserId: string;
  browserPid: number;
  profileId?: string | null;
  runtimeProfile?: string | null;
  userDataDir: string;
  url?: string | null;
  supportedOperations: string[];
  unsupportedOperations: string[];
  unsupportedCommands: ServiceRequestAction[];
}

export interface ServiceTabNewData {
  index: number;
  url: string;
}

export interface ServiceTabSwitchData {
  index: number;
  url: string;
  title: string;
}

export interface ServiceTabCloseData {
  closed: number;
  activeIndex: number;
}

export interface ServiceTabRecord {
  index: number;
  title: string;
  url: string;
  type: string;
  active: boolean;
  targetId?: string;
  sessionId?: string;
  [key: string]: unknown;
}

export interface ServiceTabListData {
  tabs: ServiceTabRecord[];
}

export interface ServiceUrlData {
  url: string;
}

export interface ServiceTitleData {
  title: string;
}

export interface ServiceSnapshotRef {
  role: string;
  name: string;
  [key: string]: unknown;
}

export interface ServiceSnapshotData {
  snapshot: string;
  origin: string;
  refs: Record<string, ServiceSnapshotRef>;
}

export interface ServiceScreenshotAnnotationBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ServiceScreenshotAnnotation {
  ref: string;
  number: number;
  role: string;
  name?: string;
  box: ServiceScreenshotAnnotationBox;
}

export interface ServiceScreenshotData {
  path: string;
  annotations?: ServiceScreenshotAnnotation[];
}

export interface ServiceTextData {
  text: string;
  origin?: string;
}

export interface ServiceValueData {
  value: unknown;
  origin?: string;
}

export interface ServiceHtmlData {
  html: string;
}

export interface ServiceVisibilityData {
  visible: boolean;
  origin: string;
}

export interface ServiceEnabledData {
  enabled: boolean;
  origin: string;
}

export interface ServiceCheckedData {
  checked: boolean;
  origin: string;
}

export interface ServiceCountData {
  count: number;
  selector: string;
}

export interface ServiceBoundingBoxData {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ServiceStylesData {
  styles: Record<string, string>;
}

export interface ServiceClickData {
  clicked: string;
  newTab?: boolean;
  url?: string;
  fallbackNavigation?: boolean;
  deferredActivation?: boolean;
}

export interface ServiceFillData {
  filled: string;
}

export interface ServiceTypeData {
  typed: string;
}

export interface ServicePressData {
  pressed: string;
}

export interface ServiceHoverData {
  hovered: string;
}

export interface ServiceScrollData {
  scrolled: true;
}

export interface ServiceSelectData {
  selected: string[];
}

export interface ServiceCheckData {
  checked: string;
}

export interface ServiceUncheckData {
  unchecked: string;
}

export type ServiceWaitData =
  | { waited: "text"; text: string }
  | { waited: "selector"; selector: string }
  | { waited: "url"; url: string }
  | { waited: "function" }
  | { waited: "load"; state: string }
  | { waited: "timeout"; ms: number };

export interface ServiceFocusData {
  focused: string;
}

export interface ServiceClearData {
  cleared: string;
}

export interface ServiceScrollIntoViewData {
  scrolled: string;
}

export interface ServiceSetData {
  set: true;
}

export interface ServiceOfflineData {
  offline: boolean;
}

export interface ServiceViewportData {
  width: number;
  height: number;
  deviceScaleFactor: number;
  mobile: boolean;
}

export interface ServiceUserAgentData {
  userAgent: string;
}

export interface ServiceTimezoneData {
  timezoneId: string;
}

export interface ServiceLocaleData {
  locale: string;
}

export interface ServiceGeolocationData {
  latitude: number;
  longitude: number;
}

export interface ServicePermissionsData {
  granted: string[];
}

export type ServiceDialogData =
  | { hasDialog: true; type: string; message: string; defaultPrompt?: string }
  | { hasDialog: false }
  | { handled: true; accepted: boolean };

export type ServiceClipboardData =
  | { text: unknown }
  | { written: string }
  | { copied: true }
  | { pasted: true };

export interface ServiceUploadData {
  uploaded: number;
  selector: string;
}

export interface ServiceCookieRecord {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number;
  size?: number;
  httpOnly?: boolean;
  secure?: boolean;
  session?: boolean;
  sameSite?: string;
  [key: string]: unknown;
}

export interface ServiceCookiesData {
  cookies: ServiceCookieRecord[];
}

export interface ServiceClearedData {
  cleared: true;
}

export type ServiceStorageGetData =
  | { key: string; value: unknown }
  | { data: Record<string, unknown> };

export interface ServiceConsoleMessage {
  type: string;
  text: string;
  args?: unknown[];
  [key: string]: unknown;
}

export interface ServiceConsoleData {
  messages: ServiceConsoleMessage[];
}

export interface ServiceErrorEntry {
  text: string;
  url?: string | null;
  line?: number | null;
  column?: number | null;
  [key: string]: unknown;
}

export interface ServiceErrorsData {
  errors: ServiceErrorEntry[];
}

export interface ServicePathData {
  path: string;
}

export interface ServiceResponseBodyData {
  body: string;
  status: number;
  headers: Record<string, unknown>;
}

export interface ServiceHarStartData {
  started: true;
}

export interface ServiceHarStopData {
  path: string;
  requestCount: number;
}

export interface ServiceRouteData {
  routed: string;
}

export interface ServiceUnrouteData {
  unrouted: string;
}

export interface ServiceTrackedRequest {
  url: string;
  method: string;
  headers: Record<string, unknown>;
  timestamp: number;
  resourceType: string;
  requestId: string;
  postData?: string;
  status?: number;
  responseHeaders?: Record<string, unknown>;
  mimeType?: string;
  responseBody?: string;
  [key: string]: unknown;
}

export interface ServiceRequestsData {
  requests: ServiceTrackedRequest[];
}

export interface ServiceRequestActionDataMap {
  navigate: ServiceNavigateData;
  cdp_free_launch: ServiceCdpFreeLaunchData;
  back: ServiceUrlData;
  forward: ServiceUrlData;
  reload: ServiceUrlData;
  tab_new: ServiceTabNewData;
  tab_switch: ServiceTabSwitchData;
  tab_close: ServiceTabCloseData;
  tab_list: ServiceTabListData;
  url: ServiceUrlData;
  title: ServiceTitleData;
  snapshot: ServiceSnapshotData;
  screenshot: ServiceScreenshotData;
  gettext: ServiceTextData;
  inputvalue: ServiceValueData;
  isvisible: ServiceVisibilityData;
  getattribute: ServiceValueData;
  innerhtml: ServiceHtmlData;
  styles: ServiceStylesData;
  count: ServiceCountData;
  boundingbox: ServiceBoundingBoxData;
  isenabled: ServiceEnabledData;
  ischecked: ServiceCheckedData;
  click: ServiceClickData;
  fill: ServiceFillData;
  type: ServiceTypeData;
  press: ServicePressData;
  hover: ServiceHoverData;
  scroll: ServiceScrollData;
  select: ServiceSelectData;
  check: ServiceCheckData;
  uncheck: ServiceUncheckData;
  wait: ServiceWaitData;
  focus: ServiceFocusData;
  clear: ServiceClearData;
  scrollintoview: ServiceScrollIntoViewData;
  setcontent: ServiceSetData;
  headers: ServiceSetData;
  offline: ServiceOfflineData;
  viewport: ServiceViewportData;
  user_agent: ServiceUserAgentData;
  timezone: ServiceTimezoneData;
  locale: ServiceLocaleData;
  geolocation: ServiceGeolocationData;
  permissions: ServicePermissionsData;
  emulatemedia: ServiceSetData;
  dialog: ServiceDialogData;
  clipboard: ServiceClipboardData;
  upload: ServiceUploadData;
  cookies_get: ServiceCookiesData;
  cookies_set: ServiceSetData;
  cookies_clear: ServiceClearedData;
  storage_get: ServiceStorageGetData;
  storage_set: ServiceSetData;
  storage_clear: ServiceClearedData;
  console: ServiceConsoleData | ServiceClearedData;
  errors: ServiceErrorsData;
  download: ServicePathData;
  waitfordownload: ServicePathData;
  pdf: ServicePathData;
  responsebody: ServiceResponseBodyData;
  har_start: ServiceHarStartData;
  har_stop: ServiceHarStopData;
  route: ServiceRouteData;
  unroute: ServiceUnrouteData;
  requests: ServiceRequestsData | ServiceClearedData;
  request_detail: ServiceTrackedRequest;
}

export type ServiceRequestDataForAction<TAction extends ServiceRequestAction> =
  TAction extends keyof ServiceRequestActionDataMap ? ServiceRequestActionDataMap[TAction] : unknown;

export interface ServiceRequestResponse<TData = unknown> {
  id?: string;
  success: boolean;
  data?: TData;
  error?: unknown;
  warning?: unknown;
  [key: string]: unknown;
}

export interface ServiceTabAccessPlan {
  readinessSummary?: {
    manualSeedingRequired?: boolean;
  };
  seedingHandoff?: {
    command?: string;
  } | null;
  decision: {
    manualSeedingRequired?: boolean;
    serviceRequest: {
      request: ServiceRequestForAction<"tab_new">;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface ServiceMonitorRunDueSummary {
  targetServiceIds?: string[];
  matched?: number;
  monitorIds?: string[];
  resultStates?: string[];
  staleProfileIds?: string[];
  freshTargetServiceIds?: string[];
  expiredTargetServiceIds?: string[];
  unverifiedTargetServiceIds?: string[];
  succeeded?: boolean;
  failed?: boolean;
  recommendedAction?: string;
  matchingResults?: unknown[];
  [key: string]: unknown;
}

export interface ServiceTabRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  accessPlan?: ServiceTabAccessPlan;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  monitorRunDueSummary?: ServiceMonitorRunDueSummary;
  url?: string;
  params?: Record<string, unknown>;
}

export interface ServiceTabRequestHttpOptions extends ServiceTabRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceCdpFreeLaunchRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  accessPlan?: ServiceTabAccessPlan;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  monitorRunDueSummary?: ServiceMonitorRunDueSummary;
  url?: string;
  params?: Record<string, unknown>;
}

export interface ServiceCdpFreeLaunchRequestHttpOptions extends ServiceCdpFreeLaunchRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export declare const SERVICE_REQUEST_ACTIONS: readonly ServiceRequestAction[];
export declare const SERVICE_REQUEST_REQUIRED_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_ARRAY_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_INTEGER_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_BOOLEAN_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_OBJECT_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_MCP_TOOL_NAME: "service_request";

export declare function createServiceRequest<TRequest extends ServiceRequest>(input: TRequest): TRequest;
export declare function createServiceRequestMcpToolCall(input: ServiceRequest): ServiceRequestMcpToolCall;
export declare function postServiceRequest<TRequest extends ServiceRequest>(
  options: ServiceRequestHttpOptions<TRequest>,
): Promise<ServiceRequestResponse<ServiceRequestDataForAction<TRequest["action"]>>>;
export declare function createServiceTabRequest(input: ServiceTabRequestOptions): ServiceRequestForAction<"tab_new">;
export declare function createServiceTabRequestFromAccessPlan(
  accessPlan: ServiceTabAccessPlan,
  input?: Omit<ServiceTabRequestOptions, "accessPlan">,
): ServiceRequestForAction<"tab_new">;
export declare function createServiceCdpFreeLaunchRequest(
  input: ServiceCdpFreeLaunchRequestOptions,
): ServiceRequestForAction<"cdp_free_launch">;
export declare function requestServiceTab(options: ServiceTabRequestHttpOptions): Promise<ServiceRequestResponse<ServiceTabNewData>>;
export declare function requestServiceCdpFreeLaunch(
  options: ServiceCdpFreeLaunchRequestHttpOptions,
): Promise<ServiceRequestResponse<ServiceCdpFreeLaunchData>>;
