// Generated by scripts/generate-service-observability-client.js from docs/dev/contracts/service-*.json.
// Do not edit by hand.

export type ServiceJobState =
  | "queued"
  | "waiting_profile_lease"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "timed_out";

export type ServiceJobPriority =
  | "low"
  | "normal"
  | "lifecycle";

export type ServiceNamingWarning =
  | "missing_service_name"
  | "missing_agent_name"
  | "missing_task_name";

export type ServiceIncidentState =
  | "active"
  | "recovered"
  | "service";

export type ServiceIncidentSeverity =
  | "info"
  | "warning"
  | "error"
  | "critical";

export type ServiceIncidentEscalation =
  | "none"
  | "browser_degraded"
  | "browser_recovery"
  | "job_attention"
  | "monitor_attention"
  | "service_triage"
  | "os_degraded_possible";

export type ServiceIncidentHandlingState =
  | "open"
  | "acknowledged"
  | "resolved";

export type ServiceEventKind =
  | "reconciliation"
  | "browser_launch_recorded"
  | "browser_health_changed"
  | "browser_recovery_started"
  | "browser_recovery_override"
  | "tab_lifecycle_changed"
  | "profile_lease_wait_started"
  | "profile_lease_wait_ended"
  | "reconciliation_error"
  | "incident_acknowledged"
  | "incident_resolved";

export type ServiceBrowserHealthState =
  | "not_started"
  | "launching"
  | "ready"
  | "degraded"
  | "unreachable"
  | "process_exited"
  | "cdp_disconnected"
  | "reconnecting"
  | "closing"
  | "faulted";


export interface ServiceJobRecord {
  id: string;
  action: string;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  targetServiceId: string | null;
  siteId: string | null;
  loginId: string | null;
  targetServiceIds: string[];
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  target: unknown;
  owner: unknown;
  state: ServiceJobState;
  priority: ServiceJobPriority;
  submittedAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  timeoutMs: number | null;
  result: unknown;
  error: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileRecord {
  id: string;
  name: string;
  userDataDir: string | null;
  targetReadiness: ServiceProfileTargetReadiness[];
  [key: string]: unknown;
}

export interface ServiceProfileSourceRecord {
  id: string;
  source: 'config' | 'runtime_observed' | 'persisted_state';
  overrideable: boolean;
  precedence: Array<'config' | 'runtime_observed' | 'persisted_state'>;
  [key: string]: unknown;
}

export interface ServiceProfileTargetReadiness {
  targetServiceId: string;
  loginId: string | null;
  state:
    | 'unknown'
    | 'needs_manual_seeding'
    | 'seeded_unknown_freshness'
    | 'fresh'
    | 'stale'
    | 'blocked_by_attached_devtools'
    | string;
  manualSeedingRequired: boolean;
  evidence: string;
  recommendedAction: string;
  seedingMode?: 'not_required' | 'detached_headed_no_cdp' | 'attachable_ok' | string;
  cdpAttachmentAllowedDuringSeeding?: boolean;
  preferredKeyring?: 'basic_password_store' | 'real_os_keychain' | 'managed_vault' | 'manual_login_profile' | string | null;
  setupScopes?: Array<'signin' | 'chrome_sync' | 'passkeys' | 'browser_plugins' | string>;
  lastVerifiedAt: string | null;
  freshnessExpiresAt: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileAllocation {
  profileId: string;
  profileName: string;
  allocation: string;
  keyring: string;
  targetServiceIds: string[];
  authenticatedServiceIds: string[];
  targetReadiness: ServiceProfileTargetReadiness[];
  sharedServiceIds: string[];
  holderSessionIds: string[];
  holderCount: number;
  exclusiveHolderSessionIds: string[];
  waitingJobIds: string[];
  waitingJobCount: number;
  conflictSessionIds: string[];
  leaseState: 'available' | 'shared' | 'exclusive' | 'waiting' | 'conflicted' | string;
  recommendedAction: string;
  serviceNames: string[];
  agentNames: string[];
  taskNames: string[];
  browserIds: string[];
  tabIds: string[];
  [key: string]: unknown;
}

export interface ServiceBrowserRecord {
  id: string;
  profileId: string | null;
  health: ServiceBrowserHealthState;
  [key: string]: unknown;
}

export interface ServiceSessionRecord {
  id: string;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  profileId: string | null;
  profileSelectionReason: 'explicit_profile' | 'authenticated_target' | 'target_match' | 'service_allow_list' | null;
  profileLeaseDisposition: 'new_browser' | 'reused_browser' | 'active_lease_conflict' | null;
  profileLeaseConflictSessionIds: string[];
  [key: string]: unknown;
}

export interface ServiceTabRecord {
  id: string;
  browserId: string | null;
  sessionId: string | null;
  lifecycle: string;
  [key: string]: unknown;
}

export interface ServiceMonitorRecord {
  id: string;
  name: string;
  target: Record<string, string>;
  intervalMs: number;
  state: 'active' | 'paused' | 'faulted' | string;
  lastCheckedAt: string | null;
  lastSucceededAt: string | null;
  lastFailedAt: string | null;
  lastResult: string | null;
  consecutiveFailures: number;
  [key: string]: unknown;
}

export interface ServiceMonitorSummary {
  total: number;
  active: number;
  paused: number;
  faulted: number;
  failing: number;
  repeatedFailures: number;
  neverChecked: number;
  failingMonitorIds: string[];
  repeatedFailureMonitorIds: string[];
  neverCheckedMonitorIds: string[];
  lastFailedAt: string | null;
  [key: string]: unknown;
}

export interface ServiceMonitorFilters {
  state: 'active' | 'paused' | 'faulted' | null;
  failedOnly: boolean;
  summary: boolean;
  [key: string]: unknown;
}

export interface ServiceSitePolicyRecord {
  id: string;
  originPattern: string | null;
  [key: string]: unknown;
}

export interface ServiceSitePolicySourceRecord {
  id: string;
  source: 'config' | 'persisted_state' | 'builtin';
  overrideable: boolean;
  precedence: Array<'config' | 'persisted_state' | 'builtin'>;
  [key: string]: unknown;
}

export interface ServiceProviderRecord {
  id: string;
  kind: string;
  displayName: string | null;
  enabled: boolean;
  [key: string]: unknown;
}

export interface ServiceChallengeRecord {
  id: string;
  tabId: string | null;
  kind: string;
  state: string;
  [key: string]: unknown;
}

export interface ServiceEventRecord {
  id: string;
  timestamp: string;
  kind: ServiceEventKind;
  message: string;
  browserId: string | null;
  profileId: string | null;
  sessionId: string | null;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  previousHealth: ServiceBrowserHealthState | null;
  currentHealth: ServiceBrowserHealthState | null;
  details: unknown;
  [key: string]: unknown;
}

export interface ServiceIncidentRecord {
  id: string;
  browserId: string | null;
  monitorId: string | null;
  monitorTarget: Record<string, string> | null;
  monitorResult: string | null;
  label: string;
  state: ServiceIncidentState;
  severity: ServiceIncidentSeverity;
  escalation: ServiceIncidentEscalation;
  recommendedAction: string;
  acknowledgedAt: string | null;
  acknowledgedBy: string | null;
  acknowledgementNote: string | null;
  resolvedAt: string | null;
  resolvedBy: string | null;
  resolutionNote: string | null;
  latestTimestamp: string;
  latestMessage: string;
  latestKind: string;
  currentHealth: ServiceBrowserHealthState | null;
  eventIds: string[];
  jobIds: string[];
  [key: string]: unknown;
}

export interface ServiceListResponse<TRecord> {
  count: number;
  matched?: number;
  total?: number;
  [key: string]: unknown;
}

export interface ServiceJobsResponse extends ServiceListResponse<ServiceJobRecord> {
  jobs: ServiceJobRecord[];
  job?: ServiceJobRecord;
}

export interface ServiceControlPlaneStatus {
  worker_state?: string;
  browser_health?: string;
  queue_depth?: number;
  queue_capacity?: number;
  waiting_profile_lease_job_count?: number;
  service_job_timeout_ms?: number | null;
  service_monitor_interval_ms?: number | null;
  [key: string]: unknown;
}

export interface ServiceStatusResponse {
  control_plane?: ServiceControlPlaneStatus;
  service_state: Record<string, unknown>;
  profileAllocations: ServiceProfileAllocation[];
  [key: string]: unknown;
}

export interface ServiceContractEndpoint {
  method?: string;
  route?: string;
  tool?: string;
  argumentsSchemaId?: string;
  toolCallSchemaId?: string;
  [key: string]: unknown;
}

export interface ServiceContractRecord {
  version: string;
  schemaId: string;
  schemaPath?: string;
  http?: ServiceContractEndpoint;
  mcp?: ServiceContractEndpoint;
  actions?: string[];
  actionCount?: number;
  tool?: string;
  [key: string]: unknown;
}

export interface ServiceContractsResponse {
  schemaVersion: string;
  contracts: Record<string, ServiceContractRecord>;
  http: Record<string, unknown>;
  mcp: Record<string, unknown>;
  [key: string]: unknown;
}

export interface ServiceProfilesResponse extends ServiceListResponse<ServiceProfileRecord> {
  profiles: ServiceProfileRecord[];
  profileSources: ServiceProfileSourceRecord[];
  profileAllocations: ServiceProfileAllocation[];
}

export interface ServiceProfileAllocationResponse {
  profileAllocation: ServiceProfileAllocation;
  [key: string]: unknown;
}

export interface ServiceProfileReadinessResponse {
  profileId: string;
  targetReadiness: ServiceProfileTargetReadiness[];
  count: number;
  [key: string]: unknown;
}

export interface ServiceProfileSeedingHandoffResponse {
  profileId: string;
  profileName: string;
  targetServiceId: string;
  loginId: string | null;
  manualSeedingRequired: boolean;
  seedingMode: 'not_required' | 'detached_headed_no_cdp' | 'attachable_ok' | string;
  cdpAttachmentAllowedDuringSeeding: boolean;
  preferredKeyring: 'basic_password_store' | 'real_os_keychain' | 'managed_vault' | 'manual_login_profile' | string | null;
  setupScopes: Array<'signin' | 'chrome_sync' | 'passkeys' | 'browser_plugins' | string>;
  recommendedAction: string;
  url: string;
  command: string;
  lifecycle: ServiceProfileSeedingHandoffLifecycle;
  operatorSteps: string[];
  operatorIntervention: ServiceProfileSeedingOperatorIntervention;
  warnings: string[];
  [key: string]: unknown;
}

export type ServiceProfileSeedingHandoffState =
  | 'not_required'
  | 'needs_manual_seeding'
  | 'seeding_launched_detached'
  | 'seeding_waiting_for_close'
  | 'completion_declared_waiting_for_close'
  | 'seeding_closed_unverified'
  | 'verification_pending'
  | 'fresh'
  | 'failed'
  | 'abandoned'
  | string;

export interface ServiceProfileSeedingHandoffLifecycle {
  id: string;
  profileId: string;
  targetServiceId: string;
  state: ServiceProfileSeedingHandoffState;
  pid: number | null;
  startedAt: string | null;
  expiresAt: string | null;
  lastPromptedAt: string | null;
  declaredCompleteAt: string | null;
  closedAt: string | null;
  updatedAt: string | null;
  actor: string | null;
  note: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileSeedingOperatorIntervention {
  state: ServiceProfileSeedingHandoffState;
  severity: 'info' | 'attention' | 'action_required' | 'danger' | string;
  title: string;
  message: string;
  ownedBy: 'agent-browser' | string;
  defaultChannels: Array<'api' | 'mcp' | 'dashboard' | 'desktop' | 'webhook' | 'agent' | string>;
  optionalChannels: Array<'api' | 'mcp' | 'dashboard' | 'desktop' | 'webhook' | 'agent' | string>;
  desktopPopupPolicy: 'disabled' | 'optional_policy_controlled' | 'required' | string;
  blocksProfileLease: boolean;
  completionSignals: Array<
    'seeding_browser_closed' | 'operator_or_agent_declared_complete' | 'post_seeding_probe_records_freshness' | string
  >;
  actions: ServiceProfileSeedingOperatorAction[];
  [key: string]: unknown;
}

export interface ServiceProfileSeedingOperatorAction {
  id: string;
  label: string;
  kind: 'operator_command' | 'operator_instruction' | 'service_request' | 'operator_remedy' | string;
  safety: 'safe' | 'caution' | 'danger' | string;
  description: string;
  command?: string;
  [key: string]: unknown;
}

export interface ServiceProfileSeedingHandoffOptions extends ServiceIdOptions {
  targetServiceId?: string;
}

export interface ServiceProfileSeedingHandoffUpdateOptions extends ServiceProfileSeedingHandoffOptions {
  state?: ServiceProfileSeedingHandoffState;
  pid?: number;
  startedAt?: string;
  expiresAt?: string;
  lastPromptedAt?: string;
  declaredCompleteAt?: string;
  closedAt?: string;
  actor?: string;
  note?: string;
}

export interface ServiceProfileSeedingHandoffUpdateResponse {
  id: string;
  profileId: string;
  targetServiceId: string;
  handoff: ServiceProfileSeedingHandoffLifecycle;
  seedingHandoff: ServiceProfileSeedingHandoffResponse;
  updated: boolean;
  [key: string]: unknown;
}

export interface ServiceBrowsersResponse extends ServiceListResponse<ServiceBrowserRecord> {
  browsers: ServiceBrowserRecord[];
}

export interface ServiceSessionsResponse extends ServiceListResponse<ServiceSessionRecord> {
  sessions: ServiceSessionRecord[];
}

export interface ServiceTabsResponse extends ServiceListResponse<ServiceTabRecord> {
  tabs: ServiceTabRecord[];
}

export interface ServiceMonitorsResponse extends ServiceListResponse<ServiceMonitorRecord> {
  monitors: ServiceMonitorRecord[];
  filters?: ServiceMonitorFilters;
  summary?: ServiceMonitorSummary;
}

export interface ServiceSitePoliciesResponse extends ServiceListResponse<ServiceSitePolicyRecord> {
  sitePolicies: ServiceSitePolicyRecord[];
  sitePolicySources: ServiceSitePolicySourceRecord[];
}

export interface ServiceProvidersResponse extends ServiceListResponse<ServiceProviderRecord> {
  providers: ServiceProviderRecord[];
}

export interface ServiceChallengesResponse extends ServiceListResponse<ServiceChallengeRecord> {
  challenges: ServiceChallengeRecord[];
}

export interface ServiceReconcileResponse {
  reconciled: boolean;
  service_state: Record<string, unknown>;
  [key: string]: unknown;
}

export interface ServiceProfileUpsertResponse {
  id: string;
  upserted: boolean;
  profile: ServiceProfileRecord;
  [key: string]: unknown;
}

export interface ServiceProfileDeleteResponse {
  id: string;
  deleted: boolean;
  profile: ServiceProfileRecord | null;
  [key: string]: unknown;
}

export interface ServiceSessionUpsertResponse {
  id: string;
  upserted: boolean;
  session: ServiceSessionRecord;
  [key: string]: unknown;
}

export interface ServiceSessionDeleteResponse {
  id: string;
  deleted: boolean;
  session: ServiceSessionRecord | null;
  [key: string]: unknown;
}

export interface ServiceSitePolicyUpsertResponse {
  id: string;
  upserted: boolean;
  sitePolicy: ServiceSitePolicyRecord;
  [key: string]: unknown;
}

export interface ServiceSitePolicyDeleteResponse {
  id: string;
  deleted: boolean;
  sitePolicy: ServiceSitePolicyRecord | null;
  [key: string]: unknown;
}

export interface ServiceProviderUpsertResponse {
  id: string;
  upserted: boolean;
  provider: ServiceProviderRecord;
  [key: string]: unknown;
}

export interface ServiceProviderDeleteResponse {
  id: string;
  deleted: boolean;
  provider: ServiceProviderRecord | null;
  [key: string]: unknown;
}

export interface ServiceMonitorUpsertResponse {
  id: string;
  upserted: boolean;
  monitor: ServiceMonitorRecord;
  [key: string]: unknown;
}

export interface ServiceMonitorDeleteResponse {
  id: string;
  deleted: boolean;
  monitor: ServiceMonitorRecord | null;
  [key: string]: unknown;
}

export interface ServiceMonitorRunDueResponse {
  checked: number;
  succeeded: number;
  failed: number;
  monitorIds: string[];
  [key: string]: unknown;
}

export interface ServiceMonitorStateResponse {
  id: string;
  monitor: ServiceMonitorRecord;
  state: 'active' | 'paused' | 'faulted' | string;
  updated: boolean;
  [key: string]: unknown;
}

export interface ServiceMonitorTriageResponse extends ServiceMonitorStateResponse {
  resetFailures: boolean;
  acknowledged: boolean;
  incident: ServiceIncidentRecord | null;
}

export interface ServiceRemediesApplyResponse {
  applied: boolean;
  escalation: 'browser_degraded' | 'monitor_attention' | 'os_degraded_possible';
  count: number;
  monitorIds: string[];
  monitorResults: ServiceMonitorTriageResponse[];
  browserIds: string[];
  browserResults: Array<ServiceBrowserRetryResponse & { id: string }>;
  [key: string]: unknown;
}

export interface ServiceJobCancelResponse {
  cancelled: boolean;
  job: ServiceJobRecord;
  [key: string]: unknown;
}

export interface ServiceBrowserRetryResponse {
  retryEnabled: boolean;
  browser: ServiceBrowserRecord;
  incident: ServiceIncidentRecord | null;
  [key: string]: unknown;
}

export interface ServiceIncidentAcknowledgeResponse {
  acknowledged: boolean;
  incident: ServiceIncidentRecord;
  [key: string]: unknown;
}

export interface ServiceIncidentResolveResponse {
  resolved: boolean;
  incident: ServiceIncidentRecord;
  [key: string]: unknown;
}

export interface ServiceEventsResponse extends ServiceListResponse<ServiceEventRecord> {
  events: ServiceEventRecord[];
}

export interface ServiceIncidentSummaryGroup {
  escalation: string;
  severity: string;
  state: string;
  count: number;
  latestTimestamp: string;
  recommendedAction: string;
  incidentIds: string[];
  browserIds: string[];
  monitorIds: string[];
  remedyApplyCommand: string | null;
  [key: string]: unknown;
}

export interface ServiceIncidentSummary {
  groupCount: number;
  groups: ServiceIncidentSummaryGroup[];
  [key: string]: unknown;
}

export interface ServiceIncidentsResponse extends ServiceListResponse<ServiceIncidentRecord> {
  incidents: ServiceIncidentRecord[];
  incident?: ServiceIncidentRecord;
  events?: ServiceEventRecord[];
  jobs?: ServiceJobRecord[];
  summary?: ServiceIncidentSummary;
  filters?: Record<string, unknown>;
}

export interface ServiceIncidentActivityResponse {
  incident: ServiceIncidentRecord;
  activity: Record<string, unknown>[];
  count: number;
  [key: string]: unknown;
}

export interface ServiceTraceProfileLeaseWait {
  jobId: string;
  profileId: string | null;
  outcome: string;
  startedAt: string | null;
  endedAt: string | null;
  waitedMs: number | null;
  retryAfterMs: number | null;
  conflictSessionIds: string[];
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  [key: string]: unknown;
}

export interface ServiceTraceProfileLeaseWaitSummary {
  count: number;
  activeCount: number;
  completedCount: number;
  waits: ServiceTraceProfileLeaseWait[];
  [key: string]: unknown;
}

export interface ServiceTraceSummaryContext {
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  browserId: string | null;
  profileId: string | null;
  sessionId: string | null;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  eventCount: number;
  jobCount: number;
  incidentCount: number;
  activityCount: number;
  targetIdentityCount: number;
  targetServiceIds: string[];
  latestTimestamp: string | null;
  [key: string]: unknown;
}

export interface ServiceTraceSummary {
  contextCount: number;
  hasTraceContext: boolean;
  namingWarningCount: number;
  profileLeaseWaits: ServiceTraceProfileLeaseWaitSummary;
  contexts: ServiceTraceSummaryContext[];
  [key: string]: unknown;
}

export interface ServiceTraceResponse {
  filters: Record<string, unknown>;
  events: ServiceEventRecord[];
  jobs: ServiceJobRecord[];
  incidents: ServiceIncidentRecord[];
  activity: Record<string, unknown>[];
  summary: ServiceTraceSummary;
  counts: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  matched: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  total: Record<'events' | 'jobs' | 'incidents', number>;
  [key: string]: unknown;
}

export interface ServiceObservabilityHttpOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceQueryOptions extends ServiceObservabilityHttpOptions {
  query?: Record<string, string | number | boolean | null | undefined>;
}

export interface ServiceMonitorQueryOptions extends ServiceQueryOptions {
  state?: 'active' | 'paused' | 'faulted';
  failedOnly?: boolean;
  summary?: boolean;
}

export interface ServiceIdOptions extends ServiceObservabilityHttpOptions {
  id: string;
}

export interface ServiceProfileMutationOptions extends ServiceIdOptions {
  profile: Record<string, unknown>;
}

export interface ServiceLoginProfileRegistrationOptions extends ServiceObservabilityHttpOptions {
  id: string;
  serviceName: string;
  loginId?: string;
  siteId?: string;
  targetServiceId?: string;
  targetServiceIds?: string[];
  authenticatedServiceIds?: string[];
  sharedServiceIds?: string[];
  targetReadiness?: ServiceProfileTargetReadiness[];
  readinessState?: ServiceProfileTargetReadiness['state'];
  readinessEvidence?: string;
  readinessRecommendedAction?: string;
  lastVerifiedAt?: string | null;
  freshnessExpiresAt?: string | null;
  name?: string;
  allocation?: string;
  keyring?: string;
  persistent?: boolean;
  authenticated?: boolean;
  userDataDir?: string;
  profile?: Record<string, unknown>;
}

export interface ServiceProfileReadinessMonitorRecipeOptions {
  id?: string;
  serviceName?: string;
  loginId?: string;
  siteId?: string;
  targetServiceId?: string;
  targetServiceIds?: string[];
  name?: string;
  intervalMs?: number;
  state?: ServiceMonitorRecord['state'];
  monitor?: Record<string, unknown>;
}

export interface ServiceProfileReadinessMonitorOptions
  extends ServiceObservabilityHttpOptions,
    ServiceProfileReadinessMonitorRecipeOptions {}

export interface ServiceProfileFreshnessUpdateOptions extends ServiceObservabilityHttpOptions {
  id: string;
  loginId?: string;
  siteId?: string;
  targetServiceId?: string;
  targetServiceIds?: string[];
  readinessState?: ServiceProfileTargetReadiness['state'];
  readinessEvidence?: string;
  readinessRecommendedAction?: string;
  lastVerifiedAt?: string | null;
  freshnessExpiresAt?: string | null;
  updateAuthenticatedServiceIds?: boolean;
}

export interface ServiceProfileReadinessSummary {
  /** True when at least one target explicitly needs detached manual profile seeding. */
  needsManualSeeding: boolean;
  /** True when any readiness row requires manual seeding before authenticated automation. */
  manualSeedingRequired: boolean;
  /** Target service or login IDs that need operator attention. */
  targetServiceIds: string[];
  /** Operator-facing recommended action codes returned by the service. */
  recommendedActions: string[];
}

export interface ServiceAccessPlanFreshnessUpdate {
  /** True when the plan selected a managed profile that can accept freshness evidence. */
  available: boolean;
  /** True when the caller should report bounded-probe evidence before authenticated work proceeds. */
  recommendedAfterProbe: boolean;
  /** Selected managed profile ID to update, or null when no profile was selected. */
  profileId: string | null;
  /** Target identities the freshness evidence should describe. */
  targetServiceIds: string[];
  http: {
    method: 'POST';
    route: string | null;
    routeTemplate: '/api/service/profiles/<id>/freshness';
    [key: string]: unknown;
  };
  mcp: {
    tool: 'service_profile_freshness_update';
    [key: string]: unknown;
  };
  client: {
    package: '@agent-browser/client/service-observability';
    helper: 'updateServiceProfileFreshness';
    [key: string]: unknown;
  };
  requestFields: string[];
  [key: string]: unknown;
}

export interface ServiceAccessPlanServiceRequest {
  /** True when this planned tab request can be sent immediately. */
  available: boolean;
  /** True when the same request is recommended after manual seeding or challenge work completes. */
  recommendedAfterManualAction: boolean;
  /** True when the request is blocked until operator or provider work completes. */
  blockedByManualAction: boolean;
  /** True when site policy or challenge state denies the request. */
  blockedByPolicy: boolean;
  action: 'tab_new';
  /** Profile selected by the planner, or null when no managed profile matched. */
  selectedProfileId: string | null;
  /** Lease policy the planner recommends for service-owned queue coordination. */
  profileLeasePolicy: 'wait';
  /** Copyable POST /api/service/request payload for the planned tab request. */
  request: {
    action: 'tab_new';
    serviceName?: string;
    agentName?: string;
    taskName?: string;
    targetServiceIds?: string[];
    profileLeasePolicy: 'wait';
    [key: string]: unknown;
  };
  http: {
    method: 'POST';
    route: '/api/service/request';
    [key: string]: unknown;
  };
  mcp: {
    tool: 'service_request';
    [key: string]: unknown;
  };
  client: {
    package: '@agent-browser/client/service-request';
    helper: 'requestServiceTab';
    [key: string]: unknown;
  };
  requestFields: string[];
  [key: string]: unknown;
}

export interface ServiceAccessPlanMonitorFindings {
  profileReadinessAttentionRequired: boolean;
  profileReadinessIncidentIds: string[];
  profileReadinessMonitorIds: string[];
  profileReadinessResults: string[];
  targetServiceIds: string[];
  [key: string]: unknown;
}

export interface ServiceAccessPlanDecision {
  recommendedAction: string;
  browserHost: string | null;
  interactionMode: string | null;
  challengePolicy: string | null;
  profileId: string | null;
  manualActionRequired: boolean;
  manualSeedingRequired: boolean;
  monitorAttentionRequired: boolean;
  providerIds: string[];
  challengeIds: string[];
  freshnessUpdate: ServiceAccessPlanFreshnessUpdate;
  serviceRequest: ServiceAccessPlanServiceRequest;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  reasons: string[];
  [key: string]: unknown;
}

export interface ServiceProfileIdentityMatchOptions {
  /** Calling service name, for example "JournalDownloader" or "CanvaCLI". */
  serviceName?: string;
  /** Desired login identity or site login scope, for example "acs" or "canva". */
  loginId?: string;
  /** Desired site identity alias. Treated like a target service ID for profile selection. */
  siteId?: string;
  /** Desired target site or identity provider, for example "google", "microsoft", or "canva". */
  targetServiceId?: string;
  /** Additional desired login identities. */
  loginIds?: string[];
  /** Additional desired site identities. */
  siteIds?: string[];
  /** Additional desired target site or identity-provider IDs. */
  targetServiceIds?: string[];
}

export interface ServiceProfileIdentityMatchResult {
  profile: ServiceProfileRecord | null;
  reason: 'authenticated_target' | 'target_match' | 'service_allow_list' | null;
  matchedField: 'authenticatedServiceIds' | 'targetServiceIds' | 'sharedServiceIds' | null;
  matchedIdentity: string | null;
}

export interface ServiceProfileIdentityLookupOptions extends ServiceQueryOptions, ServiceProfileIdentityMatchOptions {
  /** Optional explicit profile ID whose readiness rows should be included with the lookup response. */
  readinessProfileId?: string;
}

export interface ServiceAccessPlanOptions extends ServiceProfileIdentityLookupOptions {
  /** Calling agent name for multi-agent traceability. */
  agentName?: string;
  /** Caller task name for queue and trace debugging. */
  taskName?: string;
  /** Optional site-policy ID when the caller wants a specific policy recommendation. */
  sitePolicyId?: string;
  /** Optional challenge ID when planning around one retained challenge. */
  challengeId?: string;
}

export interface ServiceProfileAcquisitionOptions extends ServiceAccessPlanOptions {
  /** Optional fallback profile ID to register when the access plan has no selected profile. */
  registerProfileId?: string;
  /** Optional user-data directory for the fallback profile registration. */
  profileUserDataDir?: string;
  /** Whether fallback registration should mark requested targets authenticated. Defaults to registerServiceLoginProfile behavior. */
  registerAuthenticated?: boolean;
  /** Add the standard retained profile-readiness monitor after fallback registration. */
  registerReadinessMonitor?: boolean;
  /** Optional monitor ID for the retained profile-readiness monitor. */
  readinessMonitorId?: string;
  /** Optional monitor interval in milliseconds. */
  readinessMonitorIntervalMs?: number;
  /** Optional display name for fallback profile registration. */
  profileName?: string;
  /** Additional profile fields to merge into fallback profile registration. */
  profile?: Record<string, unknown>;
}

export interface ServiceProfileAcquisitionResult {
  initialAccessPlan: ServiceAccessPlanResponse;
  accessPlan: ServiceAccessPlanResponse;
  selectedProfile: ServiceProfileRecord | null;
  profileRegistration: ServiceProfileUpsertResponse | null;
  profileReadinessMonitor: ServiceMonitorUpsertResponse | null;
  registered: boolean;
  monitorRegistered: boolean;
}

export interface ServiceProfileLookupQuery {
  serviceName: string | null;
  targetServiceIds: string[];
  readinessProfileId: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileLookupMatch {
  profileId: string;
  profile: ServiceProfileRecord;
  reason: 'authenticated_target' | 'target_match' | 'service_allow_list';
  matchedField: 'authenticatedServiceIds' | 'targetServiceIds' | 'sharedServiceIds' | null;
  matchedIdentity: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileLookupResponse {
  /** Normalized lookup query after login, site, and target aliases have been folded together. */
  query: ServiceProfileLookupQuery;
  /** Server-selected profile, or null when agent-browser has no suitable managed profile. */
  selectedProfile: ServiceProfileRecord | null;
  /** Provenance for the selected profile after config, runtime observation, and persisted state are layered. */
  selectedProfileSource: ServiceProfileSourceRecord | null;
  /** Match metadata explaining the selected profile and selector reason. */
  selectedProfileMatch: ServiceProfileLookupMatch | null;
  /** Optional no-launch readiness rows for the selected or requested readiness profile. */
  readiness: ServiceProfileReadinessResponse | null;
  /** Compact manual-seeding summary suitable for operator UI or logs. */
  readinessSummary: ServiceProfileReadinessSummary;
  /** Operator-ready detached profile seeding handoff when readiness requires manual seeding. */
  seedingHandoff: ServiceProfileSeedingHandoffResponse | null;
  [key: string]: unknown;
}

export interface ServiceAccessPlanQuery extends ServiceProfileLookupQuery {
  agentName: string | null;
  taskName: string | null;
  sitePolicyId: string | null;
  challengeId: string | null;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
}

export interface ServiceSitePolicySource {
  id: string;
  source: 'config' | 'persisted_state' | 'builtin';
  matchedBy: 'explicit_site_policy_id' | 'target_service_id' | 'profile_site_policy_id';
  overrideable: boolean;
  precedence: Array<'config' | 'persisted_state' | 'builtin'>;
  [key: string]: unknown;
}

export interface ServiceAccessPlanResponse {
  /** Normalized access-plan query after login, site, and target aliases have been folded together. */
  query: ServiceAccessPlanQuery;
  /** Server-selected profile, or null when agent-browser has no suitable managed profile. */
  selectedProfile: ServiceProfileRecord | null;
  /** Provenance for the selected profile after config, runtime observation, and persisted state are layered. */
  selectedProfileSource: ServiceProfileSourceRecord | null;
  /** Match metadata explaining the selected profile and selector reason. */
  selectedProfileMatch: ServiceProfileLookupMatch | null;
  /** Optional no-launch readiness rows for the selected or requested readiness profile. */
  readiness: ServiceProfileReadinessResponse | null;
  /** Compact manual-seeding summary suitable for operator UI or logs. */
  readinessSummary: ServiceProfileReadinessSummary;
  /** Operator-ready detached profile seeding handoff when readiness requires manual seeding. */
  seedingHandoff: ServiceProfileSeedingHandoffResponse | null;
  /** Active monitor findings relevant to this access-plan request. */
  monitorFindings: ServiceAccessPlanMonitorFindings;
  /** Site policy selected for this request, or null when none matches. */
  sitePolicy: ServiceSitePolicyRecord | null;
  /** Provenance for the selected site policy after config, persisted state, and built-ins are layered. */
  sitePolicySource: ServiceSitePolicySource | null;
  /** Enabled providers relevant to the selected profile, site policy, or challenge. */
  providers: ServiceProviderRecord[];
  /** Retained non-resolved challenges or the explicit requested challenge. */
  challenges: ServiceChallengeRecord[];
  /** Service-owned recommendation before any browser launch or control request. */
  decision: ServiceAccessPlanDecision;
  [key: string]: unknown;
}

export interface ServiceSessionMutationOptions extends ServiceIdOptions {
  session: Record<string, unknown>;
}

export interface ServiceSitePolicyMutationOptions extends ServiceIdOptions {
  sitePolicy: Record<string, unknown>;
}

export interface ServiceProviderMutationOptions extends ServiceIdOptions {
  provider: Record<string, unknown>;
}

export interface ServiceMonitorMutationOptions extends ServiceIdOptions {
  monitor: Record<string, unknown>;
}

export interface ServiceMonitorTriageOptions extends ServiceIdOptions {
  by?: string;
  note?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
}

export interface ServiceRemediesApplyOptions extends ServiceObservabilityHttpOptions {
  escalation?: 'browser_degraded' | 'monitor_attention' | 'os_degraded_possible';
  by?: string;
  note?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
}

export interface ServiceJobCancelOptions extends ServiceObservabilityHttpOptions {
  jobId: string;
}

export interface ServiceBrowserRetryOptions extends ServiceObservabilityHttpOptions {
  browserId: string;
  by?: string;
  note?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
}

export interface ServiceIncidentMutationOptions extends ServiceObservabilityHttpOptions {
  incidentId: string;
  by?: string;
  note?: string;
}

export interface ServiceIncidentActivityOptions extends ServiceObservabilityHttpOptions {
  incidentId: string;
}

export declare const SERVICE_JOB_STATES: readonly string[];
export declare const SERVICE_JOB_PRIORITIES: readonly string[];
export declare const SERVICE_NAMING_WARNINGS: readonly string[];
export declare const SERVICE_INCIDENT_STATES: readonly string[];
export declare const SERVICE_INCIDENT_SEVERITIES: readonly string[];
export declare const SERVICE_INCIDENT_ESCALATIONS: readonly string[];
export declare const SERVICE_INCIDENT_HANDLING_STATES: readonly string[];
export declare const SERVICE_EVENT_KINDS: readonly string[];
export declare const SERVICE_BROWSER_HEALTH_STATES: readonly string[];

export declare function getServiceStatus(options: ServiceObservabilityHttpOptions): Promise<ServiceStatusResponse>;
export declare function getServiceContracts(options: ServiceObservabilityHttpOptions): Promise<ServiceContractsResponse>;
export declare function getServiceProfiles(options: ServiceQueryOptions): Promise<ServiceProfilesResponse>;
export declare function getServiceProfileAllocation(options: ServiceIdOptions): Promise<ServiceProfileAllocationResponse>;
/** Read one profile's no-launch target readiness rows. */
export declare function getServiceProfileReadiness(options: ServiceIdOptions): Promise<ServiceProfileReadinessResponse>;
/** Read the operator-ready detached profile seeding handoff for one profile. */
export declare function getServiceProfileSeedingHandoff(options: ServiceProfileSeedingHandoffOptions): Promise<ServiceProfileSeedingHandoffResponse>;
/** Persist lifecycle state for a CDP-free profile seeding handoff. */
export declare function updateServiceProfileSeedingHandoff(options: ServiceProfileSeedingHandoffUpdateOptions): Promise<ServiceProfileSeedingHandoffUpdateResponse>;
export declare function summarizeServiceProfileReadiness(readiness?: ServiceProfileReadinessResponse | null): ServiceProfileReadinessSummary;
export declare function findServiceProfileForIdentity(profiles: ServiceProfileRecord[] | undefined | null, options: ServiceProfileIdentityMatchOptions): ServiceProfileIdentityMatchResult;
/** Older descriptive alias for lookupServiceProfile. */
export declare function getServiceProfileForIdentity(options: ServiceProfileIdentityLookupOptions): Promise<ServiceProfileLookupResponse>;
/** Ask agent-browser to select a managed profile by service plus login, site, or target identity. */
export declare function lookupServiceProfile(options: ServiceProfileIdentityLookupOptions): Promise<ServiceProfileLookupResponse>;
/** Ask agent-browser for the no-launch profile, policy, provider, challenge, and readiness recommendation. */
export declare function getServiceAccessPlan(options: ServiceAccessPlanOptions): Promise<ServiceAccessPlanResponse>;
/** Broker-first helper that access-plans, optionally registers a fallback profile, optionally adds a readiness monitor, and returns the refreshed recommendation. */
export declare function acquireServiceLoginProfile(options: ServiceProfileAcquisitionOptions): Promise<ServiceProfileAcquisitionResult>;
export declare function getServiceBrowsers(options: ServiceQueryOptions): Promise<ServiceBrowsersResponse>;
export declare function getServiceSessions(options: ServiceQueryOptions): Promise<ServiceSessionsResponse>;
export declare function getServiceTabs(options: ServiceQueryOptions): Promise<ServiceTabsResponse>;
export declare function getServiceMonitors(options: ServiceMonitorQueryOptions): Promise<ServiceMonitorsResponse>;
/** Ask the service to run due active monitor checks immediately. */
export declare function runDueServiceMonitors(options: ServiceObservabilityHttpOptions): Promise<ServiceMonitorRunDueResponse>;
export declare function getServiceSitePolicies(options: ServiceQueryOptions): Promise<ServiceSitePoliciesResponse>;
export declare function getServiceProviders(options: ServiceQueryOptions): Promise<ServiceProvidersResponse>;
export declare function getServiceChallenges(options: ServiceQueryOptions): Promise<ServiceChallengesResponse>;
export declare function postServiceReconcile(options: ServiceObservabilityHttpOptions): Promise<ServiceReconcileResponse>;
export declare function upsertServiceProfile(options: ServiceProfileMutationOptions): Promise<ServiceProfileUpsertResponse>;
export declare function registerServiceLoginProfile(options: ServiceLoginProfileRegistrationOptions): Promise<ServiceProfileUpsertResponse>;
/** Build the standard no-launch profile-readiness monitor record for one target identity. */
export declare function createServiceProfileReadinessMonitor(options: ServiceProfileReadinessMonitorRecipeOptions): { id: string, monitor: Record<string, unknown> };
/** Upsert the standard no-launch profile-readiness monitor for one target identity. */
export declare function upsertServiceProfileReadinessMonitor(options: ServiceProfileReadinessMonitorOptions): Promise<ServiceMonitorUpsertResponse>;
/** Ask the service to merge bounded-probe freshness evidence into a profile. */
export declare function updateServiceProfileFreshness(options: ServiceProfileFreshnessUpdateOptions): Promise<ServiceProfileUpsertResponse>;
/** Record the result of a bounded post-close seeding auth probe. */
export declare function verifyServiceProfileSeeding(options: ServiceProfileFreshnessUpdateOptions): Promise<ServiceProfileUpsertResponse>;
export declare function deleteServiceProfile(options: ServiceIdOptions): Promise<ServiceProfileDeleteResponse>;
export declare function upsertServiceSession(options: ServiceSessionMutationOptions): Promise<ServiceSessionUpsertResponse>;
export declare function deleteServiceSession(options: ServiceIdOptions): Promise<ServiceSessionDeleteResponse>;
export declare function upsertServiceSitePolicy(options: ServiceSitePolicyMutationOptions): Promise<ServiceSitePolicyUpsertResponse>;
export declare function deleteServiceSitePolicy(options: ServiceIdOptions): Promise<ServiceSitePolicyDeleteResponse>;
export declare function upsertServiceMonitor(options: ServiceMonitorMutationOptions): Promise<ServiceMonitorUpsertResponse>;
export declare function deleteServiceMonitor(options: ServiceIdOptions): Promise<ServiceMonitorDeleteResponse>;
export declare function pauseServiceMonitor(options: ServiceIdOptions): Promise<ServiceMonitorStateResponse>;
export declare function resumeServiceMonitor(options: ServiceIdOptions): Promise<ServiceMonitorStateResponse>;
export declare function resetServiceMonitorFailures(options: ServiceIdOptions): Promise<ServiceMonitorStateResponse>;
export declare function triageServiceMonitor(options: ServiceMonitorTriageOptions): Promise<ServiceMonitorTriageResponse>;
export declare function upsertServiceProvider(options: ServiceProviderMutationOptions): Promise<ServiceProviderUpsertResponse>;
export declare function deleteServiceProvider(options: ServiceIdOptions): Promise<ServiceProviderDeleteResponse>;
export declare function cancelServiceJob(options: ServiceJobCancelOptions): Promise<ServiceJobCancelResponse>;
export declare function retryServiceBrowser(options: ServiceBrowserRetryOptions): Promise<ServiceBrowserRetryResponse>;
export declare function applyServiceRemedies(options: ServiceRemediesApplyOptions): Promise<ServiceRemediesApplyResponse>;
export declare function acknowledgeServiceIncident(options: ServiceIncidentMutationOptions): Promise<ServiceIncidentAcknowledgeResponse>;
export declare function resolveServiceIncident(options: ServiceIncidentMutationOptions): Promise<ServiceIncidentResolveResponse>;
export declare function getServiceJobs(options: ServiceQueryOptions): Promise<ServiceJobsResponse>;
export declare function getServiceJob(options: ServiceIdOptions): Promise<ServiceJobsResponse>;
export declare function getServiceEvents(options: ServiceQueryOptions): Promise<ServiceEventsResponse>;
export declare function getServiceIncidents(options: ServiceQueryOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncident(options: ServiceIdOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncidentActivity(options: ServiceIncidentActivityOptions): Promise<ServiceIncidentActivityResponse>;
export declare function getServiceTrace(options: ServiceQueryOptions): Promise<ServiceTraceResponse>;
