// Generated by scripts/generate-service-request-client.js from docs/dev/contracts/service-request.v1.schema.json.
// Do not edit by hand.

export type ServiceRequestAction =
  | "navigate"
  | "cdp_free_launch"
  | "back"
  | "forward"
  | "reload"
  | "tab_new"
  | "tab_switch"
  | "tab_close"
  | "view_focus"
  | "view_takeover"
  | "service_remote_view_route_checkout"
  | "service_remote_view_route_release"
  | "service_route_pool_repair"
  | "service_viewer_lease_request"
  | "service_viewer_lease_heartbeat"
  | "service_viewer_lease_release"
  | "service_controller_lease_takeover"
  | "tab_list"
  | "url"
  | "title"
  | "viewport"
  | "user_agent"
  | "emulatemedia"
  | "timezone"
  | "locale"
  | "geolocation"
  | "permissions"
  | "cookies_get"
  | "cookies_set"
  | "cookies_clear"
  | "storage_get"
  | "storage_set"
  | "storage_clear"
  | "console"
  | "errors"
  | "setcontent"
  | "headers"
  | "offline"
  | "dialog"
  | "clipboard"
  | "upload"
  | "download"
  | "waitfordownload"
  | "pdf"
  | "responsebody"
  | "har_start"
  | "har_stop"
  | "route"
  | "unroute"
  | "requests"
  | "request_detail"
  | "snapshot"
  | "screenshot"
  | "click"
  | "fill"
  | "wait"
  | "type"
  | "press"
  | "hover"
  | "select"
  | "gettext"
  | "inputvalue"
  | "isvisible"
  | "getattribute"
  | "innerhtml"
  | "styles"
  | "count"
  | "boundingbox"
  | "isenabled"
  | "ischecked"
  | "check"
  | "uncheck"
  | "scroll"
  | "scrollintoview"
  | "focus"
  | "clear"
  | "service_browser_close"
  | "service_browser_repair"
  | "service_prune_retained"
  | "service_repair_retained";

export interface ServiceRequest {
  action: ServiceRequestAction;
  params?: Record<string, unknown>;
  profileLeasePolicy?: string;
  browserBuild?: string;
  displayIsolation?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
  targetServiceId?: string;
  targetService?: string;
  siteId?: string;
  loginId?: string;
  accountId?: string;
  url?: string;
  profile?: string;
  runtimeProfile?: string;
  browserId?: string;
  sessionName?: string;
  targetServiceIds?: string[];
  targetServices?: string[];
  siteIds?: string[];
  loginIds?: string[];
  accountIds?: string[];
  jobTimeoutMs?: number;
  profileLeaseWaitTimeoutMs?: number;
  blockedByManualAction?: boolean;
  manualSeedingRequired?: boolean;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  requiresCdpFree?: boolean;
  cdpAttachmentAllowed?: boolean;
  allowDuplicateProfileLane?: boolean;
  monitorRunDueSummary?: Record<string, unknown>;
}

export type ServiceRequestForAction<TAction extends ServiceRequestAction> =
  Omit<ServiceRequest, "action"> & { action: TAction };

export interface ServiceRequestMcpToolCall {
  name: "service_request";
  arguments: ServiceRequest;
}

export interface ServiceRequestHttpOptions<TRequest extends ServiceRequest = ServiceRequest> {
  baseUrl: string;
  request: TRequest;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceNavigateData {
  url: string;
  title?: string;
}

export interface ServiceCdpFreeLaunchData {
  launched: true;
  cdpFree: true;
  cdpAttachmentAllowed: false;
  browserId: string;
  browserPid: number;
  profileId?: string | null;
  runtimeProfile?: string | null;
  userDataDir: string;
  url?: string | null;
  supportedOperations: string[];
  unsupportedOperations: string[];
  unsupportedCommands: ServiceRequestAction[];
}

export interface ServiceCdpFreeLaunchAvailability {
  controlPlaneMode: "cdp_free";
  lifecycleOnly: true;
  cdpAttachmentAllowed: boolean;
  supportedOperations: string[];
  unsupportedOperations: string[];
  unsupportedCommands: ServiceRequestAction[];
  availableCommands: ServiceRequestAction[];
  hasUnsupportedCommandList: boolean;
}

export interface ServiceTabNewData {
  index: number;
  url: string;
}

export interface ServiceTabSwitchData {
  index: number;
  url: string;
  title: string;
}

export interface ServiceTabCloseData {
  closed: number;
  activeIndex: number;
}

export interface ServiceViewFocusData {
  broughtToFront: boolean;
  maximizeRequested: boolean;
  maximized: boolean;
  windowId?: number;
  maximizeError?: string;
  tabSwitch?: ServiceTabSwitchData;
}

export interface ServiceViewTakeoverData {
  takeoverRequested: boolean;
  reconnectRequested: boolean;
  browserProcessPreserved: boolean;
  browserId: string;
  sessionName: string;
  streamId?: string | null;
  provider?: string | null;
  openMode?: string;
  reason?: string;
  targetId?: string | null;
  index?: number | null;
  requestedAt?: string;
}

export interface ServiceRemoteViewRouteMutationData {
  status: string;
  routeId?: string;
  remoteViewRouteId?: string;
  displayAllocationId?: string;
  routePoolEntryId?: string | null;
  browserId?: string;
  sessionName?: string;
  frameUrl?: string | null;
  externalUrl?: string | null;
  providerMode?: string;
  remoteViewRoute?: Record<string, unknown> | null;
  routePoolEntry?: Record<string, unknown> | null;
  releasedViewerLeaseIds?: string[];
  updatedAt?: string;
  [key: string]: unknown;
}

export interface ServiceRoutePoolRepairData {
  repaired: boolean;
  dryRun: boolean;
  observedAt?: string;
  policy?: Record<string, unknown>;
  before?: Record<string, number>;
  after?: Record<string, number>;
  candidates?: Record<string, string[]>;
  candidateReasons?: Record<string, Record<string, unknown>>;
  candidateCounts: Record<string, number>;
  skipped?: Record<string, string[]>;
  skippedCounts?: Record<string, number>;
  repairedCounts: Record<string, number>;
  recommendedNextStep?: string;
}

export interface ServiceViewerLeaseMutationData {
  status: string;
  routeId?: string | null;
  remoteViewRouteId?: string;
  viewerLeaseId?: string;
  controllerLeaseId?: string | null;
  previousControllerLeaseId?: string | null;
  viewerLease?: Record<string, unknown> | null;
  remoteViewRoute?: Record<string, unknown> | null;
  updatedAt?: string;
  [key: string]: unknown;
}

export interface ServiceTabRecord {
  index: number;
  title: string;
  url: string;
  type: string;
  active: boolean;
  targetId?: string;
  sessionId?: string;
  [key: string]: unknown;
}

export interface ServiceTabListData {
  tabs: ServiceTabRecord[];
}

export interface ServiceUrlData {
  url: string;
}

export interface ServiceTitleData {
  title: string;
}

export interface ServiceSnapshotRef {
  role: string;
  name: string;
  [key: string]: unknown;
}

export interface ServiceSnapshotData {
  snapshot: string;
  origin: string;
  refs: Record<string, ServiceSnapshotRef>;
}

export interface ServiceScreenshotAnnotationBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ServiceScreenshotAnnotation {
  ref: string;
  number: number;
  role: string;
  name?: string;
  box: ServiceScreenshotAnnotationBox;
}

export interface ServiceScreenshotData {
  path: string;
  annotations?: ServiceScreenshotAnnotation[];
}

export interface ServiceTextData {
  text: string;
  origin?: string;
}

export interface ServiceValueData {
  value: unknown;
  origin?: string;
}

export interface ServiceHtmlData {
  html: string;
}

export interface ServiceVisibilityData {
  visible: boolean;
  origin: string;
}

export interface ServiceEnabledData {
  enabled: boolean;
  origin: string;
}

export interface ServiceCheckedData {
  checked: boolean;
  origin: string;
}

export interface ServiceCountData {
  count: number;
  selector: string;
}

export interface ServiceBoundingBoxData {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ServiceStylesData {
  styles: Record<string, string>;
}

export interface ServiceClickData {
  clicked: string;
  newTab?: boolean;
  url?: string;
  fallbackNavigation?: boolean;
  deferredActivation?: boolean;
}

export interface ServiceFillData {
  filled: string;
}

export interface ServiceTypeData {
  typed: string;
}

export interface ServicePressData {
  pressed: string;
}

export interface ServiceHoverData {
  hovered: string;
}

export interface ServiceScrollData {
  scrolled: true;
}

export interface ServiceSelectData {
  selected: string[];
}

export interface ServiceCheckData {
  checked: string;
}

export interface ServiceUncheckData {
  unchecked: string;
}

export type ServiceWaitData =
  | { waited: "text"; text: string }
  | { waited: "selector"; selector: string }
  | { waited: "url"; url: string }
  | { waited: "function" }
  | { waited: "load"; state: string }
  | { waited: "timeout"; ms: number };

export interface ServiceFocusData {
  focused: string;
}

export interface ServiceClearData {
  cleared: string;
}

export interface ServiceScrollIntoViewData {
  scrolled: string;
}

export interface ServiceSetData {
  set: true;
}

export interface ServiceOfflineData {
  offline: boolean;
}

export interface ServiceViewportData {
  width: number;
  height: number;
  deviceScaleFactor: number;
  mobile: boolean;
}

export interface ServiceUserAgentData {
  userAgent: string;
}

export interface ServiceTimezoneData {
  timezoneId: string;
}

export interface ServiceLocaleData {
  locale: string;
}

export interface ServiceGeolocationData {
  latitude: number;
  longitude: number;
}

export interface ServicePermissionsData {
  granted: string[];
}

export type ServiceDialogData =
  | { hasDialog: true; type: string; message: string; defaultPrompt?: string }
  | { hasDialog: false }
  | { handled: true; accepted: boolean };

export type ServiceClipboardData =
  | { text: unknown }
  | { written: string }
  | { copied: true }
  | { pasted: true };

export interface ServiceUploadData {
  uploaded: number;
  selector: string;
}

export interface ServiceCookieRecord {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number;
  size?: number;
  httpOnly?: boolean;
  secure?: boolean;
  session?: boolean;
  sameSite?: string;
  [key: string]: unknown;
}

export interface ServiceCookiesData {
  cookies: ServiceCookieRecord[];
}

export interface ServiceClearedData {
  cleared: true;
}

export type ServiceStorageGetData =
  | { key: string; value: unknown }
  | { data: Record<string, unknown> };

export interface ServiceConsoleMessage {
  type: string;
  text: string;
  args?: unknown[];
  [key: string]: unknown;
}

export interface ServiceConsoleData {
  messages: ServiceConsoleMessage[];
}

export interface ServiceErrorEntry {
  text: string;
  url?: string | null;
  line?: number | null;
  column?: number | null;
  [key: string]: unknown;
}

export interface ServiceErrorsData {
  errors: ServiceErrorEntry[];
}

export interface ServicePathData {
  path: string;
}

export interface ServiceResponseBodyData {
  body: string;
  status: number;
  headers: Record<string, unknown>;
}

export interface ServiceHarStartData {
  started: true;
}

export interface ServiceHarStopData {
  path: string;
  requestCount: number;
}

export interface ServiceRouteData {
  routed: string;
}

export interface ServiceUnrouteData {
  unrouted: string;
}

export interface ServiceTrackedRequest {
  url: string;
  method: string;
  headers: Record<string, unknown>;
  timestamp: number;
  resourceType: string;
  requestId: string;
  postData?: string;
  status?: number;
  responseHeaders?: Record<string, unknown>;
  mimeType?: string;
  responseBody?: string;
  [key: string]: unknown;
}

export interface ServiceRequestsData {
  requests: ServiceTrackedRequest[];
}

export interface ServiceRetainedCleanupData {
  pruned?: boolean;
  repaired?: boolean;
  dryRun: boolean;
  observedAt?: string;
  policy?: Record<string, unknown>;
  before?: Record<string, number>;
  after?: Record<string, number>;
  candidates?: Record<string, string[]>;
  candidateCounts: Record<string, number>;
  skipped?: Record<string, string[]>;
  skippedCounts?: Record<string, number>;
  skippedSummary?: Record<string, unknown>;
  removed?: Record<string, number>;
  repairedCounts?: Record<string, number>;
  recommendedNextStep?: string;
}

export interface ServiceBrowserCloseData {
  closed: boolean;
  browserId: string;
  requestedBrowserId: string;
  serviceOwned: boolean;
  [key: string]: unknown;
}

export interface ServiceBrowserRepairData {
  repaired: boolean;
  browser: Record<string, unknown>;
  incident?: Record<string, unknown> | null;
}

export interface ServiceRequestActionDataMap {
  navigate: ServiceNavigateData;
  cdp_free_launch: ServiceCdpFreeLaunchData;
  back: ServiceUrlData;
  forward: ServiceUrlData;
  reload: ServiceUrlData;
  tab_new: ServiceTabNewData;
  tab_switch: ServiceTabSwitchData;
  tab_close: ServiceTabCloseData;
  view_focus: ServiceViewFocusData;
  view_takeover: ServiceViewTakeoverData;
  service_remote_view_route_checkout: ServiceRemoteViewRouteMutationData;
  service_remote_view_route_release: ServiceRemoteViewRouteMutationData;
  service_route_pool_repair: ServiceRoutePoolRepairData;
  service_viewer_lease_request: ServiceViewerLeaseMutationData;
  service_viewer_lease_heartbeat: ServiceViewerLeaseMutationData;
  service_viewer_lease_release: ServiceViewerLeaseMutationData;
  service_controller_lease_takeover: ServiceViewerLeaseMutationData;
  tab_list: ServiceTabListData;
  url: ServiceUrlData;
  title: ServiceTitleData;
  snapshot: ServiceSnapshotData;
  screenshot: ServiceScreenshotData;
  gettext: ServiceTextData;
  inputvalue: ServiceValueData;
  isvisible: ServiceVisibilityData;
  getattribute: ServiceValueData;
  innerhtml: ServiceHtmlData;
  styles: ServiceStylesData;
  count: ServiceCountData;
  boundingbox: ServiceBoundingBoxData;
  isenabled: ServiceEnabledData;
  ischecked: ServiceCheckedData;
  click: ServiceClickData;
  fill: ServiceFillData;
  type: ServiceTypeData;
  press: ServicePressData;
  hover: ServiceHoverData;
  scroll: ServiceScrollData;
  select: ServiceSelectData;
  check: ServiceCheckData;
  uncheck: ServiceUncheckData;
  wait: ServiceWaitData;
  focus: ServiceFocusData;
  clear: ServiceClearData;
  scrollintoview: ServiceScrollIntoViewData;
  setcontent: ServiceSetData;
  headers: ServiceSetData;
  offline: ServiceOfflineData;
  viewport: ServiceViewportData;
  user_agent: ServiceUserAgentData;
  timezone: ServiceTimezoneData;
  locale: ServiceLocaleData;
  geolocation: ServiceGeolocationData;
  permissions: ServicePermissionsData;
  emulatemedia: ServiceSetData;
  dialog: ServiceDialogData;
  clipboard: ServiceClipboardData;
  upload: ServiceUploadData;
  cookies_get: ServiceCookiesData;
  cookies_set: ServiceSetData;
  cookies_clear: ServiceClearedData;
  storage_get: ServiceStorageGetData;
  storage_set: ServiceSetData;
  storage_clear: ServiceClearedData;
  console: ServiceConsoleData | ServiceClearedData;
  errors: ServiceErrorsData;
  download: ServicePathData;
  waitfordownload: ServicePathData;
  pdf: ServicePathData;
  responsebody: ServiceResponseBodyData;
  har_start: ServiceHarStartData;
  har_stop: ServiceHarStopData;
  route: ServiceRouteData;
  unroute: ServiceUnrouteData;
  requests: ServiceRequestsData | ServiceClearedData;
  request_detail: ServiceTrackedRequest;
  service_browser_close: ServiceBrowserCloseData;
  service_browser_repair: ServiceBrowserRepairData;
  service_prune_retained: ServiceRetainedCleanupData;
  service_repair_retained: ServiceRetainedCleanupData;
}

export type ServiceRequestDataForAction<TAction extends ServiceRequestAction> =
  TAction extends keyof ServiceRequestActionDataMap ? ServiceRequestActionDataMap[TAction] : unknown;

export interface ServiceRequestResponse<TData = unknown> {
  id?: string;
  success: boolean;
  data?: TData;
  error?: unknown;
  warning?: unknown;
  [key: string]: unknown;
}

export interface ServiceTabAccessPlan {
  readinessSummary?: {
    manualSeedingRequired?: boolean;
  };
  seedingHandoff?: {
    command?: string;
  } | null;
  decision: {
    manualSeedingRequired?: boolean;
    serviceRequest: {
      request: ServiceRequestForAction<"tab_new">;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

export interface ServiceMonitorRunDueSummary {
  targetServiceIds?: string[];
  matched?: number;
  monitorIds?: string[];
  resultStates?: string[];
  staleProfileIds?: string[];
  freshTargetServiceIds?: string[];
  expiredTargetServiceIds?: string[];
  unverifiedTargetServiceIds?: string[];
  succeeded?: boolean;
  failed?: boolean;
  recommendedAction?: string;
  matchingResults?: unknown[];
  [key: string]: unknown;
}

export interface ServiceTabRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  accessPlan?: ServiceTabAccessPlan;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  monitorRunDueSummary?: ServiceMonitorRunDueSummary;
  url?: string;
  params?: Record<string, unknown>;
}

export interface ServiceTabRequestHttpOptions extends ServiceTabRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceCdpFreeLaunchRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  accessPlan?: ServiceTabAccessPlan;
  allowManualAction?: boolean;
  allowMonitorFreshnessRisk?: boolean;
  monitorRunDueSummary?: ServiceMonitorRunDueSummary;
  url?: string;
  params?: Record<string, unknown>;
}

export interface ServiceCdpFreeLaunchRequestHttpOptions extends ServiceCdpFreeLaunchRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceRemoteViewRouteCheckoutOptions extends Omit<ServiceRequest, "action" | "params"> {
  displayAllocationId: string;
  routeId?: string;
  remoteViewRouteId?: string;
  routePoolEntryId?: string;
  browserId?: string;
  sessionName?: string;
  streamId?: string;
  provider?: string;
  providerMode?: string;
  frameUrl?: string;
  externalUrl?: string;
  connectionId?: string;
  connectionName?: string;
  params?: Record<string, unknown>;
}

export interface ServiceRemoteViewRouteReleaseOptions extends Omit<ServiceRequest, "action" | "params"> {
  routeId: string;
  params?: Record<string, unknown>;
}

export interface ServiceRoutePoolRepairOptions extends Omit<ServiceRequest, "action" | "params"> {
  apply?: boolean;
  staleCheckouts?: boolean;
  serviceState?: Record<string, unknown>;
  params?: Record<string, unknown>;
}

export interface ServiceViewerLeaseRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  routeId: string;
  viewerId?: string;
  viewerName?: string;
  viewerRole?: "observer" | "controller" | "pending_controller" | "none" | string;
  openMode?: "embedded" | "external" | "fullscreen" | "tile" | string;
  browserId?: string;
  expiresAt?: string;
  params?: Record<string, unknown>;
}

export interface ServiceViewerLeaseReleaseOptions extends Omit<ServiceRequest, "action" | "params"> {
  viewerLeaseId: string;
  params?: Record<string, unknown>;
}

export interface ServiceViewerLeaseHeartbeatOptions extends Omit<ServiceRequest, "action" | "params"> {
  viewerLeaseId: string;
  expiresAt?: string;
  params?: Record<string, unknown>;
}

export interface ServiceControllerLeaseTakeoverOptions extends ServiceViewerLeaseRequestOptions {
  viewerLeaseId?: string;
}

export interface ServiceRemoteViewRouteCheckoutHttpOptions extends ServiceRemoteViewRouteCheckoutOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceRemoteViewRouteReleaseHttpOptions extends ServiceRemoteViewRouteReleaseOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceRoutePoolRepairHttpOptions extends ServiceRoutePoolRepairOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceViewerLeaseRequestHttpOptions extends ServiceViewerLeaseRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceViewerLeaseReleaseHttpOptions extends ServiceViewerLeaseReleaseOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceViewerLeaseHeartbeatHttpOptions extends ServiceViewerLeaseHeartbeatOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceControllerLeaseTakeoverHttpOptions extends ServiceControllerLeaseTakeoverOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export declare const SERVICE_REQUEST_ACTIONS: readonly ServiceRequestAction[];
export declare const SERVICE_REQUEST_REQUIRED_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_ARRAY_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_INTEGER_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_BOOLEAN_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_OBJECT_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_MCP_TOOL_NAME: "service_request";

export declare function createServiceRequest<TRequest extends ServiceRequest>(input: TRequest): TRequest;
export declare function createServiceRequestMcpToolCall(input: ServiceRequest): ServiceRequestMcpToolCall;
export declare function postServiceRequest<TRequest extends ServiceRequest>(
  options: ServiceRequestHttpOptions<TRequest>,
): Promise<ServiceRequestResponse<ServiceRequestDataForAction<TRequest["action"]>>>;
export declare function createServiceTabRequest(input: ServiceTabRequestOptions): ServiceRequestForAction<"tab_new">;
export declare function createServiceTabRequestFromAccessPlan(
  accessPlan: ServiceTabAccessPlan,
  input?: Omit<ServiceTabRequestOptions, "accessPlan">,
): ServiceRequestForAction<"tab_new">;
export declare function createServiceCdpFreeLaunchRequest(
  input: ServiceCdpFreeLaunchRequestOptions,
): ServiceRequestForAction<"cdp_free_launch">;
export declare function createServiceRemoteViewRouteCheckoutRequest(
  input: ServiceRemoteViewRouteCheckoutOptions,
): ServiceRequestForAction<"service_remote_view_route_checkout">;
export declare function createServiceRemoteViewRouteReleaseRequest(
  input: ServiceRemoteViewRouteReleaseOptions,
): ServiceRequestForAction<"service_remote_view_route_release">;
export declare function createServiceRoutePoolRepairRequest(
  input?: ServiceRoutePoolRepairOptions,
): ServiceRequestForAction<"service_route_pool_repair">;
export declare function createServiceViewerLeaseRequest(
  input: ServiceViewerLeaseRequestOptions,
): ServiceRequestForAction<"service_viewer_lease_request">;
export declare function createServiceViewerLeaseHeartbeatRequest(
  input: ServiceViewerLeaseHeartbeatOptions,
): ServiceRequestForAction<"service_viewer_lease_heartbeat">;
export declare function createServiceViewerLeaseReleaseRequest(
  input: ServiceViewerLeaseReleaseOptions,
): ServiceRequestForAction<"service_viewer_lease_release">;
export declare function createServiceControllerLeaseTakeoverRequest(
  input: ServiceControllerLeaseTakeoverOptions,
): ServiceRequestForAction<"service_controller_lease_takeover">;
export declare function requestServiceTab(options: ServiceTabRequestHttpOptions): Promise<ServiceRequestResponse<ServiceTabNewData>>;
export declare function requestServiceCdpFreeLaunch(
  options: ServiceCdpFreeLaunchRequestHttpOptions,
): Promise<ServiceRequestResponse<ServiceCdpFreeLaunchData>>;
export declare function requestServiceRemoteViewRouteCheckout(
  options: ServiceRemoteViewRouteCheckoutHttpOptions,
): Promise<ServiceRequestResponse<ServiceRemoteViewRouteMutationData>>;
export declare function requestServiceRemoteViewRouteRelease(
  options: ServiceRemoteViewRouteReleaseHttpOptions,
): Promise<ServiceRequestResponse<ServiceRemoteViewRouteMutationData>>;
export declare function requestServiceRoutePoolRepair(
  options: ServiceRoutePoolRepairHttpOptions,
): Promise<ServiceRequestResponse<ServiceRoutePoolRepairData>>;
export declare function requestServiceViewerLease(
  options: ServiceViewerLeaseRequestHttpOptions,
): Promise<ServiceRequestResponse<ServiceViewerLeaseMutationData>>;
export declare function heartbeatServiceViewerLease(
  options: ServiceViewerLeaseHeartbeatHttpOptions,
): Promise<ServiceRequestResponse<ServiceViewerLeaseMutationData>>;
export declare function releaseServiceViewerLease(
  options: ServiceViewerLeaseReleaseHttpOptions,
): Promise<ServiceRequestResponse<ServiceViewerLeaseMutationData>>;
export declare function takeoverServiceControllerLease(
  options: ServiceControllerLeaseTakeoverHttpOptions,
): Promise<ServiceRequestResponse<ServiceViewerLeaseMutationData>>;
export declare function summarizeServiceCdpFreeLaunchAvailability(
  data: ServiceCdpFreeLaunchData,
): ServiceCdpFreeLaunchAvailability;
export declare function isServiceCdpFreeActionAvailable(
  data: ServiceCdpFreeLaunchData,
  action: ServiceRequestAction,
): boolean;
