// Generated by scripts/generate-service-request-client.js from docs/dev/contracts/service-request.v1.schema.json.
// Do not edit by hand.

export type ServiceRequestAction =
  | "navigate"
  | "back"
  | "forward"
  | "reload"
  | "tab_new"
  | "tab_switch"
  | "tab_close"
  | "tab_list"
  | "url"
  | "title"
  | "viewport"
  | "user_agent"
  | "emulatemedia"
  | "timezone"
  | "locale"
  | "geolocation"
  | "permissions"
  | "cookies_get"
  | "cookies_set"
  | "cookies_clear"
  | "storage_get"
  | "storage_set"
  | "storage_clear"
  | "console"
  | "errors"
  | "setcontent"
  | "headers"
  | "offline"
  | "dialog"
  | "clipboard"
  | "upload"
  | "download"
  | "waitfordownload"
  | "pdf"
  | "responsebody"
  | "har_start"
  | "har_stop"
  | "route"
  | "unroute"
  | "requests"
  | "request_detail"
  | "snapshot"
  | "screenshot"
  | "click"
  | "fill"
  | "wait"
  | "type"
  | "press"
  | "hover"
  | "select"
  | "gettext"
  | "inputvalue"
  | "isvisible"
  | "getattribute"
  | "innerhtml"
  | "styles"
  | "count"
  | "boundingbox"
  | "isenabled"
  | "ischecked"
  | "check"
  | "uncheck"
  | "scroll"
  | "scrollintoview"
  | "focus"
  | "clear";

export interface ServiceRequest {
  action: ServiceRequestAction;
  params?: Record<string, unknown>;
  jobTimeoutMs?: number;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
  targetServiceId?: string;
  targetService?: string;
  siteId?: string;
  loginId?: string;
  profile?: string;
  runtimeProfile?: string;
  targetServiceIds?: string[];
  targetServices?: string[];
  siteIds?: string[];
  loginIds?: string[];
}

export type ServiceRequestForAction<TAction extends ServiceRequestAction> =
  Omit<ServiceRequest, "action"> & { action: TAction };

export interface ServiceRequestMcpToolCall {
  name: "service_request";
  arguments: ServiceRequest;
}

export interface ServiceRequestHttpOptions<TRequest extends ServiceRequest = ServiceRequest> {
  baseUrl: string;
  request: TRequest;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceNavigateData {
  url: string;
  title?: string;
}

export interface ServiceTabNewData {
  index: number;
  url: string;
}

export interface ServiceSnapshotRef {
  role: string;
  name: string;
  [key: string]: unknown;
}

export interface ServiceSnapshotData {
  snapshot: string;
  origin: string;
  refs: Record<string, ServiceSnapshotRef>;
}

export interface ServiceScreenshotAnnotationBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ServiceScreenshotAnnotation {
  ref: string;
  number: number;
  role: string;
  name?: string;
  box: ServiceScreenshotAnnotationBox;
}

export interface ServiceScreenshotData {
  path: string;
  annotations?: ServiceScreenshotAnnotation[];
}

export interface ServiceRequestActionDataMap {
  navigate: ServiceNavigateData;
  tab_new: ServiceTabNewData;
  snapshot: ServiceSnapshotData;
  screenshot: ServiceScreenshotData;
}

export type ServiceRequestDataForAction<TAction extends ServiceRequestAction> =
  TAction extends keyof ServiceRequestActionDataMap ? ServiceRequestActionDataMap[TAction] : unknown;

export interface ServiceRequestResponse<TData = unknown> {
  id?: string;
  success: boolean;
  data?: TData;
  error?: unknown;
  warning?: unknown;
  [key: string]: unknown;
}

export interface ServiceTabRequestOptions extends Omit<ServiceRequest, "action" | "params"> {
  url?: string;
  params?: Record<string, unknown>;
}

export interface ServiceTabRequestHttpOptions extends ServiceTabRequestOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export declare const SERVICE_REQUEST_ACTIONS: readonly ServiceRequestAction[];
export declare const SERVICE_REQUEST_REQUIRED_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_STRING_ARRAY_FIELDS: readonly string[];
export declare const SERVICE_REQUEST_MCP_TOOL_NAME: "service_request";

export declare function createServiceRequest<TRequest extends ServiceRequest>(input: TRequest): TRequest;
export declare function createServiceRequestMcpToolCall(input: ServiceRequest): ServiceRequestMcpToolCall;
export declare function postServiceRequest<TRequest extends ServiceRequest>(
  options: ServiceRequestHttpOptions<TRequest>,
): Promise<ServiceRequestResponse<ServiceRequestDataForAction<TRequest["action"]>>>;
export declare function createServiceTabRequest(input: ServiceTabRequestOptions): ServiceRequestForAction<"tab_new">;
export declare function requestServiceTab(options: ServiceTabRequestHttpOptions): Promise<ServiceRequestResponse<ServiceTabNewData>>;
