// Generated by scripts/generate-service-observability-client.js from docs/dev/contracts/service-*.json.
// Do not edit by hand.

export type ServiceJobState =
  | "queued"
  | "waiting_profile_lease"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "timed_out";

export type ServiceJobPriority =
  | "low"
  | "normal"
  | "lifecycle";

export type ServiceNamingWarning =
  | "missing_service_name"
  | "missing_agent_name"
  | "missing_task_name";

export type ServiceIncidentState =
  | "active"
  | "recovered"
  | "service";

export type ServiceIncidentSeverity =
  | "info"
  | "warning"
  | "error"
  | "critical";

export type ServiceIncidentEscalation =
  | "none"
  | "browser_degraded"
  | "browser_recovery"
  | "job_attention"
  | "service_triage"
  | "os_degraded_possible";

export type ServiceIncidentHandlingState =
  | "open"
  | "acknowledged"
  | "resolved";

export type ServiceEventKind =
  | "reconciliation"
  | "browser_launch_recorded"
  | "browser_health_changed"
  | "browser_recovery_started"
  | "browser_recovery_override"
  | "tab_lifecycle_changed"
  | "profile_lease_wait_started"
  | "profile_lease_wait_ended"
  | "reconciliation_error"
  | "incident_acknowledged"
  | "incident_resolved";

export type ServiceBrowserHealthState =
  | "not_started"
  | "launching"
  | "ready"
  | "degraded"
  | "unreachable"
  | "process_exited"
  | "cdp_disconnected"
  | "reconnecting"
  | "closing"
  | "faulted";


export interface ServiceJobRecord {
  id: string;
  action: string;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  target: unknown;
  owner: unknown;
  state: ServiceJobState;
  priority: ServiceJobPriority;
  submittedAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  timeoutMs: number | null;
  result: unknown;
  error: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileRecord {
  id: string;
  name: string;
  userDataDir: string | null;
  targetReadiness: ServiceProfileTargetReadiness[];
  [key: string]: unknown;
}

export interface ServiceProfileTargetReadiness {
  targetServiceId: string;
  loginId: string | null;
  state:
    | 'unknown'
    | 'needs_manual_seeding'
    | 'seeded_unknown_freshness'
    | 'fresh'
    | 'stale'
    | 'blocked_by_attached_devtools'
    | string;
  manualSeedingRequired: boolean;
  evidence: string;
  recommendedAction: string;
  lastVerifiedAt: string | null;
  freshnessExpiresAt: string | null;
  [key: string]: unknown;
}

export interface ServiceProfileAllocation {
  profileId: string;
  profileName: string;
  allocation: string;
  keyring: string;
  targetServiceIds: string[];
  authenticatedServiceIds: string[];
  targetReadiness: ServiceProfileTargetReadiness[];
  sharedServiceIds: string[];
  holderSessionIds: string[];
  holderCount: number;
  exclusiveHolderSessionIds: string[];
  waitingJobIds: string[];
  waitingJobCount: number;
  conflictSessionIds: string[];
  leaseState: 'available' | 'shared' | 'exclusive' | 'waiting' | 'conflicted' | string;
  recommendedAction: string;
  serviceNames: string[];
  agentNames: string[];
  taskNames: string[];
  browserIds: string[];
  tabIds: string[];
  [key: string]: unknown;
}

export interface ServiceBrowserRecord {
  id: string;
  profileId: string | null;
  health: ServiceBrowserHealthState;
  [key: string]: unknown;
}

export interface ServiceSessionRecord {
  id: string;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  profileId: string | null;
  profileSelectionReason: 'explicit_profile' | 'authenticated_target' | 'target_match' | 'service_allow_list' | null;
  profileLeaseDisposition: 'new_browser' | 'reused_browser' | 'active_lease_conflict' | null;
  profileLeaseConflictSessionIds: string[];
  [key: string]: unknown;
}

export interface ServiceTabRecord {
  id: string;
  browserId: string | null;
  sessionId: string | null;
  lifecycle: string;
  [key: string]: unknown;
}

export interface ServiceSitePolicyRecord {
  id: string;
  originPattern: string | null;
  [key: string]: unknown;
}

export interface ServiceProviderRecord {
  id: string;
  kind: string;
  displayName: string | null;
  enabled: boolean;
  [key: string]: unknown;
}

export interface ServiceChallengeRecord {
  id: string;
  tabId: string | null;
  kind: string;
  state: string;
  [key: string]: unknown;
}

export interface ServiceEventRecord {
  id: string;
  timestamp: string;
  kind: ServiceEventKind;
  message: string;
  browserId: string | null;
  profileId: string | null;
  sessionId: string | null;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  previousHealth: ServiceBrowserHealthState | null;
  currentHealth: ServiceBrowserHealthState | null;
  details: unknown;
  [key: string]: unknown;
}

export interface ServiceIncidentRecord {
  id: string;
  browserId: string | null;
  label: string;
  state: ServiceIncidentState;
  severity: ServiceIncidentSeverity;
  escalation: ServiceIncidentEscalation;
  recommendedAction: string;
  acknowledgedAt: string | null;
  acknowledgedBy: string | null;
  acknowledgementNote: string | null;
  resolvedAt: string | null;
  resolvedBy: string | null;
  resolutionNote: string | null;
  latestTimestamp: string;
  latestMessage: string;
  latestKind: string;
  currentHealth: ServiceBrowserHealthState | null;
  eventIds: string[];
  jobIds: string[];
  [key: string]: unknown;
}

export interface ServiceListResponse<TRecord> {
  count: number;
  matched?: number;
  total?: number;
  [key: string]: unknown;
}

export interface ServiceJobsResponse extends ServiceListResponse<ServiceJobRecord> {
  jobs: ServiceJobRecord[];
  job?: ServiceJobRecord;
}

export interface ServiceControlPlaneStatus {
  worker_state?: string;
  browser_health?: string;
  queue_depth?: number;
  queue_capacity?: number;
  waiting_profile_lease_job_count?: number;
  service_job_timeout_ms?: number | null;
  [key: string]: unknown;
}

export interface ServiceStatusResponse {
  control_plane?: ServiceControlPlaneStatus;
  service_state: Record<string, unknown>;
  profileAllocations: ServiceProfileAllocation[];
  [key: string]: unknown;
}

export interface ServiceContractEndpoint {
  method?: string;
  route?: string;
  tool?: string;
  argumentsSchemaId?: string;
  toolCallSchemaId?: string;
  [key: string]: unknown;
}

export interface ServiceContractRecord {
  version: string;
  schemaId: string;
  schemaPath?: string;
  http?: ServiceContractEndpoint;
  mcp?: ServiceContractEndpoint;
  actions?: string[];
  actionCount?: number;
  tool?: string;
  [key: string]: unknown;
}

export interface ServiceContractsResponse {
  schemaVersion: string;
  contracts: Record<string, ServiceContractRecord>;
  http: Record<string, unknown>;
  mcp: Record<string, unknown>;
  [key: string]: unknown;
}

export interface ServiceProfilesResponse extends ServiceListResponse<ServiceProfileRecord> {
  profiles: ServiceProfileRecord[];
  profileAllocations: ServiceProfileAllocation[];
}

export interface ServiceProfileAllocationResponse {
  profileAllocation: ServiceProfileAllocation;
  [key: string]: unknown;
}

export interface ServiceProfileReadinessResponse {
  profileId: string;
  targetReadiness: ServiceProfileTargetReadiness[];
  count: number;
  [key: string]: unknown;
}

export interface ServiceBrowsersResponse extends ServiceListResponse<ServiceBrowserRecord> {
  browsers: ServiceBrowserRecord[];
}

export interface ServiceSessionsResponse extends ServiceListResponse<ServiceSessionRecord> {
  sessions: ServiceSessionRecord[];
}

export interface ServiceTabsResponse extends ServiceListResponse<ServiceTabRecord> {
  tabs: ServiceTabRecord[];
}

export interface ServiceSitePoliciesResponse extends ServiceListResponse<ServiceSitePolicyRecord> {
  sitePolicies: ServiceSitePolicyRecord[];
}

export interface ServiceProvidersResponse extends ServiceListResponse<ServiceProviderRecord> {
  providers: ServiceProviderRecord[];
}

export interface ServiceChallengesResponse extends ServiceListResponse<ServiceChallengeRecord> {
  challenges: ServiceChallengeRecord[];
}

export interface ServiceReconcileResponse {
  reconciled: boolean;
  service_state: Record<string, unknown>;
  [key: string]: unknown;
}

export interface ServiceProfileUpsertResponse {
  id: string;
  upserted: boolean;
  profile: ServiceProfileRecord;
  [key: string]: unknown;
}

export interface ServiceProfileDeleteResponse {
  id: string;
  deleted: boolean;
  profile: ServiceProfileRecord | null;
  [key: string]: unknown;
}

export interface ServiceSessionUpsertResponse {
  id: string;
  upserted: boolean;
  session: ServiceSessionRecord;
  [key: string]: unknown;
}

export interface ServiceSessionDeleteResponse {
  id: string;
  deleted: boolean;
  session: ServiceSessionRecord | null;
  [key: string]: unknown;
}

export interface ServiceSitePolicyUpsertResponse {
  id: string;
  upserted: boolean;
  sitePolicy: ServiceSitePolicyRecord;
  [key: string]: unknown;
}

export interface ServiceSitePolicyDeleteResponse {
  id: string;
  deleted: boolean;
  sitePolicy: ServiceSitePolicyRecord | null;
  [key: string]: unknown;
}

export interface ServiceProviderUpsertResponse {
  id: string;
  upserted: boolean;
  provider: ServiceProviderRecord;
  [key: string]: unknown;
}

export interface ServiceProviderDeleteResponse {
  id: string;
  deleted: boolean;
  provider: ServiceProviderRecord | null;
  [key: string]: unknown;
}

export interface ServiceJobCancelResponse {
  cancelled: boolean;
  job: ServiceJobRecord;
  [key: string]: unknown;
}

export interface ServiceBrowserRetryResponse {
  retryEnabled: boolean;
  browser: ServiceBrowserRecord;
  incident: ServiceIncidentRecord | null;
  [key: string]: unknown;
}

export interface ServiceIncidentAcknowledgeResponse {
  acknowledged: boolean;
  incident: ServiceIncidentRecord;
  [key: string]: unknown;
}

export interface ServiceIncidentResolveResponse {
  resolved: boolean;
  incident: ServiceIncidentRecord;
  [key: string]: unknown;
}

export interface ServiceEventsResponse extends ServiceListResponse<ServiceEventRecord> {
  events: ServiceEventRecord[];
}

export interface ServiceIncidentSummaryGroup {
  escalation: string;
  severity: string;
  state: string;
  count: number;
  latestTimestamp: string;
  recommendedAction: string;
  incidentIds: string[];
  [key: string]: unknown;
}

export interface ServiceIncidentSummary {
  groupCount: number;
  groups: ServiceIncidentSummaryGroup[];
  [key: string]: unknown;
}

export interface ServiceIncidentsResponse extends ServiceListResponse<ServiceIncidentRecord> {
  incidents: ServiceIncidentRecord[];
  incident?: ServiceIncidentRecord;
  events?: ServiceEventRecord[];
  jobs?: ServiceJobRecord[];
  summary?: ServiceIncidentSummary;
  filters?: Record<string, unknown>;
}

export interface ServiceIncidentActivityResponse {
  incident: ServiceIncidentRecord;
  activity: Record<string, unknown>[];
  count: number;
  [key: string]: unknown;
}

export interface ServiceTraceProfileLeaseWait {
  jobId: string;
  profileId: string | null;
  outcome: string;
  startedAt: string | null;
  endedAt: string | null;
  waitedMs: number | null;
  retryAfterMs: number | null;
  conflictSessionIds: string[];
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  [key: string]: unknown;
}

export interface ServiceTraceProfileLeaseWaitSummary {
  count: number;
  activeCount: number;
  completedCount: number;
  waits: ServiceTraceProfileLeaseWait[];
  [key: string]: unknown;
}

export interface ServiceTraceSummaryContext {
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  browserId: string | null;
  profileId: string | null;
  sessionId: string | null;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  eventCount: number;
  jobCount: number;
  incidentCount: number;
  activityCount: number;
  latestTimestamp: string | null;
  [key: string]: unknown;
}

export interface ServiceTraceSummary {
  contextCount: number;
  hasTraceContext: boolean;
  namingWarningCount: number;
  profileLeaseWaits: ServiceTraceProfileLeaseWaitSummary;
  contexts: ServiceTraceSummaryContext[];
  [key: string]: unknown;
}

export interface ServiceTraceResponse {
  filters: Record<string, unknown>;
  events: ServiceEventRecord[];
  jobs: ServiceJobRecord[];
  incidents: ServiceIncidentRecord[];
  activity: Record<string, unknown>[];
  summary: ServiceTraceSummary;
  counts: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  matched: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  total: Record<'events' | 'jobs' | 'incidents', number>;
  [key: string]: unknown;
}

export interface ServiceObservabilityHttpOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceQueryOptions extends ServiceObservabilityHttpOptions {
  query?: Record<string, string | number | boolean | null | undefined>;
}

export interface ServiceIdOptions extends ServiceObservabilityHttpOptions {
  id: string;
}

export interface ServiceProfileMutationOptions extends ServiceIdOptions {
  profile: Record<string, unknown>;
}

export interface ServiceLoginProfileRegistrationOptions extends ServiceObservabilityHttpOptions {
  id: string;
  serviceName: string;
  loginId?: string;
  siteId?: string;
  targetServiceId?: string;
  targetServiceIds?: string[];
  authenticatedServiceIds?: string[];
  sharedServiceIds?: string[];
  name?: string;
  allocation?: string;
  keyring?: string;
  persistent?: boolean;
  authenticated?: boolean;
  userDataDir?: string;
  profile?: Record<string, unknown>;
}

export interface ServiceProfileReadinessSummary {
  needsManualSeeding: boolean;
  manualSeedingRequired: boolean;
  targetServiceIds: string[];
  recommendedActions: string[];
}

export interface ServiceSessionMutationOptions extends ServiceIdOptions {
  session: Record<string, unknown>;
}

export interface ServiceSitePolicyMutationOptions extends ServiceIdOptions {
  sitePolicy: Record<string, unknown>;
}

export interface ServiceProviderMutationOptions extends ServiceIdOptions {
  provider: Record<string, unknown>;
}

export interface ServiceJobCancelOptions extends ServiceObservabilityHttpOptions {
  jobId: string;
}

export interface ServiceBrowserRetryOptions extends ServiceObservabilityHttpOptions {
  browserId: string;
  by?: string;
  note?: string;
  serviceName?: string;
  agentName?: string;
  taskName?: string;
}

export interface ServiceIncidentMutationOptions extends ServiceObservabilityHttpOptions {
  incidentId: string;
  by?: string;
  note?: string;
}

export interface ServiceIncidentActivityOptions extends ServiceObservabilityHttpOptions {
  incidentId: string;
}

export declare const SERVICE_JOB_STATES: readonly string[];
export declare const SERVICE_JOB_PRIORITIES: readonly string[];
export declare const SERVICE_NAMING_WARNINGS: readonly string[];
export declare const SERVICE_INCIDENT_STATES: readonly string[];
export declare const SERVICE_INCIDENT_SEVERITIES: readonly string[];
export declare const SERVICE_INCIDENT_ESCALATIONS: readonly string[];
export declare const SERVICE_INCIDENT_HANDLING_STATES: readonly string[];
export declare const SERVICE_EVENT_KINDS: readonly string[];
export declare const SERVICE_BROWSER_HEALTH_STATES: readonly string[];

export declare function getServiceStatus(options: ServiceObservabilityHttpOptions): Promise<ServiceStatusResponse>;
export declare function getServiceContracts(options: ServiceObservabilityHttpOptions): Promise<ServiceContractsResponse>;
export declare function getServiceProfiles(options: ServiceQueryOptions): Promise<ServiceProfilesResponse>;
export declare function getServiceProfileAllocation(options: ServiceIdOptions): Promise<ServiceProfileAllocationResponse>;
export declare function getServiceProfileReadiness(options: ServiceIdOptions): Promise<ServiceProfileReadinessResponse>;
export declare function summarizeServiceProfileReadiness(readiness?: ServiceProfileReadinessResponse | null): ServiceProfileReadinessSummary;
export declare function getServiceBrowsers(options: ServiceQueryOptions): Promise<ServiceBrowsersResponse>;
export declare function getServiceSessions(options: ServiceQueryOptions): Promise<ServiceSessionsResponse>;
export declare function getServiceTabs(options: ServiceQueryOptions): Promise<ServiceTabsResponse>;
export declare function getServiceSitePolicies(options: ServiceQueryOptions): Promise<ServiceSitePoliciesResponse>;
export declare function getServiceProviders(options: ServiceQueryOptions): Promise<ServiceProvidersResponse>;
export declare function getServiceChallenges(options: ServiceQueryOptions): Promise<ServiceChallengesResponse>;
export declare function postServiceReconcile(options: ServiceObservabilityHttpOptions): Promise<ServiceReconcileResponse>;
export declare function upsertServiceProfile(options: ServiceProfileMutationOptions): Promise<ServiceProfileUpsertResponse>;
export declare function registerServiceLoginProfile(options: ServiceLoginProfileRegistrationOptions): Promise<ServiceProfileUpsertResponse>;
export declare function deleteServiceProfile(options: ServiceIdOptions): Promise<ServiceProfileDeleteResponse>;
export declare function upsertServiceSession(options: ServiceSessionMutationOptions): Promise<ServiceSessionUpsertResponse>;
export declare function deleteServiceSession(options: ServiceIdOptions): Promise<ServiceSessionDeleteResponse>;
export declare function upsertServiceSitePolicy(options: ServiceSitePolicyMutationOptions): Promise<ServiceSitePolicyUpsertResponse>;
export declare function deleteServiceSitePolicy(options: ServiceIdOptions): Promise<ServiceSitePolicyDeleteResponse>;
export declare function upsertServiceProvider(options: ServiceProviderMutationOptions): Promise<ServiceProviderUpsertResponse>;
export declare function deleteServiceProvider(options: ServiceIdOptions): Promise<ServiceProviderDeleteResponse>;
export declare function cancelServiceJob(options: ServiceJobCancelOptions): Promise<ServiceJobCancelResponse>;
export declare function retryServiceBrowser(options: ServiceBrowserRetryOptions): Promise<ServiceBrowserRetryResponse>;
export declare function acknowledgeServiceIncident(options: ServiceIncidentMutationOptions): Promise<ServiceIncidentAcknowledgeResponse>;
export declare function resolveServiceIncident(options: ServiceIncidentMutationOptions): Promise<ServiceIncidentResolveResponse>;
export declare function getServiceJobs(options: ServiceQueryOptions): Promise<ServiceJobsResponse>;
export declare function getServiceJob(options: ServiceIdOptions): Promise<ServiceJobsResponse>;
export declare function getServiceEvents(options: ServiceQueryOptions): Promise<ServiceEventsResponse>;
export declare function getServiceIncidents(options: ServiceQueryOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncident(options: ServiceIdOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncidentActivity(options: ServiceIncidentActivityOptions): Promise<ServiceIncidentActivityResponse>;
export declare function getServiceTrace(options: ServiceQueryOptions): Promise<ServiceTraceResponse>;
