// Generated by scripts/generate-service-observability-client.js from docs/dev/contracts/service-*.json.
// Do not edit by hand.

export type ServiceJobState =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "cancelled"
  | "timed_out";

export type ServiceJobPriority =
  | "low"
  | "normal"
  | "lifecycle";

export type ServiceNamingWarning =
  | "missing_service_name"
  | "missing_agent_name"
  | "missing_task_name";

export type ServiceIncidentState =
  | "active"
  | "recovered"
  | "service";

export type ServiceIncidentSeverity =
  | "info"
  | "warning"
  | "error"
  | "critical";

export type ServiceIncidentEscalation =
  | "none"
  | "browser_degraded"
  | "browser_recovery"
  | "job_attention"
  | "service_triage"
  | "os_degraded_possible";

export type ServiceIncidentHandlingState =
  | "open"
  | "acknowledged"
  | "resolved";

export type ServiceEventKind =
  | "reconciliation"
  | "browser_launch_recorded"
  | "browser_health_changed"
  | "browser_recovery_started"
  | "browser_recovery_override"
  | "tab_lifecycle_changed"
  | "reconciliation_error"
  | "incident_acknowledged"
  | "incident_resolved";

export type ServiceBrowserHealthState =
  | "not_started"
  | "launching"
  | "ready"
  | "degraded"
  | "unreachable"
  | "process_exited"
  | "cdp_disconnected"
  | "reconnecting"
  | "closing"
  | "faulted";


export interface ServiceJobRecord {
  id: string;
  action: string;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  namingWarnings: ServiceNamingWarning[];
  hasNamingWarning: boolean;
  target: unknown;
  owner: unknown;
  state: ServiceJobState;
  priority: ServiceJobPriority;
  submittedAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  timeoutMs: number | null;
  result: unknown;
  error: string | null;
  [key: string]: unknown;
}

export interface ServiceEventRecord {
  id: string;
  timestamp: string;
  kind: ServiceEventKind;
  message: string;
  browserId: string | null;
  profileId: string | null;
  sessionId: string | null;
  serviceName: string | null;
  agentName: string | null;
  taskName: string | null;
  previousHealth: ServiceBrowserHealthState | null;
  currentHealth: ServiceBrowserHealthState | null;
  details: unknown;
  [key: string]: unknown;
}

export interface ServiceIncidentRecord {
  id: string;
  browserId: string | null;
  label: string;
  state: ServiceIncidentState;
  severity: ServiceIncidentSeverity;
  escalation: ServiceIncidentEscalation;
  recommendedAction: string;
  acknowledgedAt: string | null;
  acknowledgedBy: string | null;
  acknowledgementNote: string | null;
  resolvedAt: string | null;
  resolvedBy: string | null;
  resolutionNote: string | null;
  latestTimestamp: string;
  latestMessage: string;
  latestKind: string;
  currentHealth: ServiceBrowserHealthState | null;
  eventIds: string[];
  jobIds: string[];
  [key: string]: unknown;
}

export interface ServiceListResponse<TRecord> {
  count: number;
  matched: number;
  total: number;
  [key: string]: unknown;
}

export interface ServiceJobsResponse extends ServiceListResponse<ServiceJobRecord> {
  jobs: ServiceJobRecord[];
  job?: ServiceJobRecord;
}

export interface ServiceEventsResponse extends ServiceListResponse<ServiceEventRecord> {
  events: ServiceEventRecord[];
}

export interface ServiceIncidentSummaryGroup {
  escalation: string;
  severity: string;
  state: string;
  count: number;
  latestTimestamp: string;
  recommendedAction: string;
  incidentIds: string[];
  [key: string]: unknown;
}

export interface ServiceIncidentSummary {
  groupCount: number;
  groups: ServiceIncidentSummaryGroup[];
  [key: string]: unknown;
}

export interface ServiceIncidentsResponse extends ServiceListResponse<ServiceIncidentRecord> {
  incidents: ServiceIncidentRecord[];
  incident?: ServiceIncidentRecord;
  events?: ServiceEventRecord[];
  jobs?: ServiceJobRecord[];
  summary?: ServiceIncidentSummary;
  filters?: Record<string, unknown>;
}

export interface ServiceIncidentActivityResponse {
  incident: ServiceIncidentRecord;
  activity: Record<string, unknown>[];
  count: number;
  [key: string]: unknown;
}

export interface ServiceTraceResponse {
  filters: Record<string, unknown>;
  events: ServiceEventRecord[];
  jobs: ServiceJobRecord[];
  incidents: ServiceIncidentRecord[];
  activity: Record<string, unknown>[];
  summary: Record<string, unknown>;
  counts: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  matched: Record<'events' | 'jobs' | 'incidents' | 'activity', number>;
  total: Record<'events' | 'jobs' | 'incidents', number>;
  [key: string]: unknown;
}

export interface ServiceObservabilityHttpOptions {
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
  signal?: AbortSignal;
}

export interface ServiceQueryOptions extends ServiceObservabilityHttpOptions {
  query?: Record<string, string | number | boolean | null | undefined>;
}

export interface ServiceIdOptions extends ServiceObservabilityHttpOptions {
  id: string;
}

export interface ServiceIncidentActivityOptions extends ServiceObservabilityHttpOptions {
  incidentId: string;
}

export declare const SERVICE_JOB_STATES: readonly string[];
export declare const SERVICE_JOB_PRIORITIES: readonly string[];
export declare const SERVICE_NAMING_WARNINGS: readonly string[];
export declare const SERVICE_INCIDENT_STATES: readonly string[];
export declare const SERVICE_INCIDENT_SEVERITIES: readonly string[];
export declare const SERVICE_INCIDENT_ESCALATIONS: readonly string[];
export declare const SERVICE_INCIDENT_HANDLING_STATES: readonly string[];
export declare const SERVICE_EVENT_KINDS: readonly string[];
export declare const SERVICE_BROWSER_HEALTH_STATES: readonly string[];

export declare function getServiceJobs(options: ServiceQueryOptions): Promise<ServiceJobsResponse>;
export declare function getServiceJob(options: ServiceIdOptions): Promise<ServiceJobsResponse>;
export declare function getServiceEvents(options: ServiceQueryOptions): Promise<ServiceEventsResponse>;
export declare function getServiceIncidents(options: ServiceQueryOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncident(options: ServiceIdOptions): Promise<ServiceIncidentsResponse>;
export declare function getServiceIncidentActivity(options: ServiceIncidentActivityOptions): Promise<ServiceIncidentActivityResponse>;
export declare function getServiceTrace(options: ServiceQueryOptions): Promise<ServiceTraceResponse>;
